BEGIN TRANSACTION;
CREATE TABLE groups(id INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(64), info varchar(128), pos int);
INSERT INTO "groups" VALUES(1,'','',1);
INSERT INTO "groups" VALUES(2,'Controls','Controls',2);
INSERT INTO "groups" VALUES(3,'Mathematics','Mathematics',6);
INSERT INTO "groups" VALUES(4,'Tools','Tools',3);
INSERT INTO "groups" VALUES(5,'Strings','Strings',4);
INSERT INTO "groups" VALUES(6,'Logic','Logic',5);
INSERT INTO "groups" VALUES(7,'DataBase','DataBase',7);
INSERT INTO "groups" VALUES(8,'LowLevel','LowLevel',8);
INSERT INTO "groups" VALUES(9,'Internet','Internet',9);
INSERT INTO "groups" VALUES(10,'Files','Files',10);
INSERT INTO "groups" VALUES(11,'Enumerations','Enumerations',11);
INSERT INTO "groups" VALUES(12,'Arrays','Arrays',12);
INSERT INTO "groups" VALUES(13,'Components','Components',13);
INSERT INTO "groups" VALUES(14,'System','System',14);
INSERT INTO "groups" VALUES(15,'Console','Console',15);
INSERT INTO "groups" VALUES(16,'Helpers','Helpers',16);
INSERT INTO "groups" VALUES(17,'MultiThread','MultiThread',17);
INSERT INTO "groups" VALUES(18,'Adobe','Adobe',18);
INSERT INTO "groups" VALUES(19,'Graphics','Graphics',19);
INSERT INTO "groups" VALUES(20,'Interfaces','Interfaces',20);
INSERT INTO "groups" VALUES(21,'ClassMembers','ClassMembers',21);
INSERT INTO "groups" VALUES(22,'Cryptography','Cryptography',22);
INSERT INTO "groups" VALUES(23,'Multimedia','Multimedia',24);
INSERT INTO "groups" VALUES(24,'EyeOne','EyeOne',25);
INSERT INTO "groups" VALUES(25,'Inherit','Inherit',26);
INSERT INTO "groups" VALUES(26,'GTK','Gtk+ Widgets',27);
INSERT INTO "groups" VALUES(27,'SDK','SDK',28);
INSERT INTO "groups" VALUES(28,'Core','Core',28);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('groups',28);
INSERT INTO "sqlite_sequence" VALUES('elements',956);
CREATE TABLE elements(id INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(64), info varchar(64), tab int, pos int, hash varchar(32));
INSERT INTO "elements" VALUES(1,'EntryPoint','Entry point',1,1,NULL);
INSERT INTO "elements" VALUES(2,'Button','Button control',2,2,NULL);
INSERT INTO "elements" VALUES(3,'Edit','Text box control',1,2,NULL);
INSERT INTO "elements" VALUES(4,'Message','Message box control',1,15,NULL);
INSERT INTO "elements" VALUES(5,'DoData','Writes data to flow',4,1,NULL);
INSERT INTO "elements" VALUES(6,'Hub','Flow manager',4,3,NULL);
INSERT INTO "elements" VALUES(7,'StrCat','String concatenation',5,2,NULL);
INSERT INTO "elements" VALUES(8,'Memory','Writes data to memory cell',4,2,NULL);
INSERT INTO "elements" VALUES(9,'For','Conditional operation loop',6,2,NULL);
INSERT INTO "elements" VALUES(10,'TimeCounter','Time counter',1,29,NULL);
INSERT INTO "elements" VALUES(11,'Timer','Programmable interval timer',13,3,NULL);
INSERT INTO "elements" VALUES(12,'If_else','Raising an event on the condition',6,3,NULL);
INSERT INTO "elements" VALUES(13,'Math','Mathematical operations',6,4,NULL);
INSERT INTO "elements" VALUES(14,'Label','Text label control',2,4,NULL);
INSERT INTO "elements" VALUES(15,'CheckBox','Check box control',2,5,NULL);
INSERT INTO "elements" VALUES(16,'WebBrowser','Web browser control',2,6,NULL);
INSERT INTO "elements" VALUES(17,'ProgressBar','Progress bar control',2,7,NULL);
INSERT INTO "elements" VALUES(18,'Copy','Copying a specified part of string',5,3,NULL);
INSERT INTO "elements" VALUES(19,'Delete','Removing a specified part of string',1,38,NULL);
INSERT INTO "elements" VALUES(20,'Insert','Inserts substring',5,5,NULL);
INSERT INTO "elements" VALUES(21,'Length','Calculates length of string',5,6,NULL);
INSERT INTO "elements" VALUES(22,'Position','Searching a text position',5,7,NULL);
INSERT INTO "elements" VALUES(23,'StrCase','Converts to lower or upper case',5,8,NULL);
INSERT INTO "elements" VALUES(24,'ODBC','ODBC access',1,16,NULL);
INSERT INTO "elements" VALUES(25,'ODBC_exec','ODBC execute request',1,17,NULL);
INSERT INTO "elements" VALUES(26,'ODBC_enumRS','Enumerates record set',1,18,NULL);
INSERT INTO "elements" VALUES(27,'FieldRead','Reading fields',8,2,NULL);
INSERT INTO "elements" VALUES(28,'RadioButton','RadioButton control',2,8,NULL);
INSERT INTO "elements" VALUES(29,'HTTP_Get','HTTP web request',9,2,NULL);
INSERT INTO "elements" VALUES(30,'ComboBox','Combo box control',2,9,NULL);
INSERT INTO "elements" VALUES(31,'Random','Random number generator',6,5,NULL);
INSERT INTO "elements" VALUES(32,'*Files_Dialogs','File dialog controls',10,1,NULL);
INSERT INTO "elements" VALUES(33,'OpenFileDialog','Opens file dialog',10,2,NULL);
INSERT INTO "elements" VALUES(34,'SDialog','Save file dialog',1,19,NULL);
INSERT INTO "elements" VALUES(35,'Browse','Browse for folder dialog',1,14,NULL);
INSERT INTO "elements" VALUES(36,'IndexToChannel','Raises event by index',4,6,NULL);
INSERT INTO "elements" VALUES(37,'ChannelToIndex','Returns index of flow',4,7,NULL);
INSERT INTO "elements" VALUES(38,'Convertor','Converts data to target type',4,8,NULL);
INSERT INTO "elements" VALUES(39,'StrList','String list',5,9,NULL);
INSERT INTO "elements" VALUES(40,'FieldWrite','Writes data to field',8,3,NULL);
INSERT INTO "elements" VALUES(41,'ItemsControl','Items Collection manager',1,21,NULL);
INSERT INTO "elements" VALUES(42,'DialogResult','Result value of a dialog box',11,1,NULL);
INSERT INTO "elements" VALUES(43,'Cursors','Built in cursors',11,2,NULL);
INSERT INTO "elements" VALUES(44,'Stack','Simple LIFO stack',4,9,NULL);
INSERT INTO "elements" VALUES(45,'Application','Manage an application',14,13,NULL);
INSERT INTO "elements" VALUES(46,'ArrayList','Collection of objects accessed by index',12,15,NULL);
INSERT INTO "elements" VALUES(47,'ForEach','Iterate over elements in collection',6,6,NULL);
INSERT INTO "elements" VALUES(48,'FormatStr','String formatting',5,10,NULL);
INSERT INTO "elements" VALUES(49,'Queue','Simple FIFO queue',4,10,NULL);
INSERT INTO "elements" VALUES(50,'Process','Manage system processes',13,1,NULL);
INSERT INTO "elements" VALUES(51,'FileSystemWatcher','File system monitoring',10,61,NULL);
INSERT INTO "elements" VALUES(52,'Dictionary','Collection of strings accessed by string',12,16,NULL);
INSERT INTO "elements" VALUES(53,'BackgroundWorker','Executes on separate thread',13,31,NULL);
INSERT INTO "elements" VALUES(54,'Comparator','Data comparator',4,13,NULL);
INSERT INTO "elements" VALUES(55,'HelpProvider','Provides pop-up or online Help for controls',13,43,NULL);
INSERT INTO "elements" VALUES(56,'StrArray','Array of strings',12,17,NULL);
INSERT INTO "elements" VALUES(57,'IntArray','Array of numbers',1,34,NULL);
INSERT INTO "elements" VALUES(58,'TextBox','Text box control',2,3,NULL);
INSERT INTO "elements" VALUES(59,'ControlStyles','Style and behavior of a control',11,3,NULL);
INSERT INTO "elements" VALUES(60,'*FileTools','File tools',10,30,NULL);
INSERT INTO "elements" VALUES(61,'FileTools','The file operations',10,31,NULL);
INSERT INTO "elements" VALUES(62,'Path','The operations path',10,23,NULL);
INSERT INTO "elements" VALUES(63,'Directory','Basic steps with a directory',10,11,NULL);
INSERT INTO "elements" VALUES(64,'Replace','All instances of OldValue are replaced with NewValue',5,11,NULL);
INSERT INTO "elements" VALUES(65,'FileStream','Provides method for the creation and opening of files',10,40,NULL);
INSERT INTO "elements" VALUES(66,'StreamCopy','Copying of FileStream',10,42,NULL);
INSERT INTO "elements" VALUES(67,'FileRW','Read/Write operation with binary file',10,32,NULL);
INSERT INTO "elements" VALUES(68,'FileTextRW','Read/Write operation with the text file',10,33,NULL);
INSERT INTO "elements" VALUES(69,'FileLinesRW','Read/Write the text file from/to the array of strings',10,34,NULL);
INSERT INTO "elements" VALUES(70,'FileAttrManage','Get/Set attributes of the file',10,36,NULL);
INSERT INTO "elements" VALUES(71,'FileACL','Get/Set ACL for a specified file',10,37,NULL);
INSERT INTO "elements" VALUES(72,'FileReplace','Replaces the contents of a specified file',10,39,NULL);
INSERT INTO "elements" VALUES(73,'FileTime','Changes the date and time of a specified file',10,38,NULL);
INSERT INTO "elements" VALUES(74,'*String_Tools','String operations',5,1,NULL);
INSERT INTO "elements" VALUES(75,'*Regex','Regular Expressions',5,35,NULL);
INSERT INTO "elements" VALUES(76,'REMatch','Searching the first occurrences of a specified regular expression',5,36,NULL);
INSERT INTO "elements" VALUES(77,'REMatches','Searching all occurrences of a specified regular expression',5,37,NULL);
INSERT INTO "elements" VALUES(78,'REMatchNext','Gets the next match',5,38,NULL);
INSERT INTO "elements" VALUES(79,'REMatchResult','Gets the expansion of a specified replacement pattern',5,39,NULL);
INSERT INTO "elements" VALUES(80,'Trim','String trimming',5,12,NULL);
INSERT INTO "elements" VALUES(81,'Environment','The current environment',14,2,NULL);
INSERT INTO "elements" VALUES(82,'*DateTime','DateTime',14,27,NULL);
INSERT INTO "elements" VALUES(83,'DateTime','Represents an instant in time',14,28,NULL);
INSERT INTO "elements" VALUES(84,'DateTimeParser','Converts the string to DateTime',14,29,NULL);
INSERT INTO "elements" VALUES(85,'DateTimeAdd','Adds a specified time interval',14,30,NULL);
INSERT INTO "elements" VALUES(86,'TimeSpan','Represents a time interval',14,31,NULL);
INSERT INTO "elements" VALUES(87,'TimeSpanParser','Converts the string to TimeSpan',14,32,NULL);
INSERT INTO "elements" VALUES(88,'DaysInMonth','Number of days in the month',14,33,NULL);
INSERT INTO "elements" VALUES(89,'DateTimeCompare','Compares DateTimes',14,34,NULL);
INSERT INTO "elements" VALUES(90,'DateTimePart','Components of DateTime',14,35,NULL);
INSERT INTO "elements" VALUES(91,'DayOfWeek','Day of the week',11,4,NULL);
INSERT INTO "elements" VALUES(92,'Console','Console entry point',1,3,NULL);
INSERT INTO "elements" VALUES(93,'ConsoleBeep','Plays the sound of a beep',15,1,NULL);
INSERT INTO "elements" VALUES(94,'ConsoleCurPosition','Position of the cursor',1,43,NULL);
INSERT INTO "elements" VALUES(95,'ConsoleKeyInfo','Console key that was pressed',15,2,NULL);
INSERT INTO "elements" VALUES(96,'ConsoleWinPosition','Position of the console window',1,44,NULL);
INSERT INTO "elements" VALUES(97,'ConsoleMoveBuffer','Moves the screen buffer',15,3,NULL);
INSERT INTO "elements" VALUES(98,'ConsoleWinSize','Size of the console window',1,45,NULL);
INSERT INTO "elements" VALUES(99,'ConsoleBufferSize','Size of screen buffer area',1,46,NULL);
INSERT INTO "elements" VALUES(100,'ConsoleKey','Standard keys on a console',15,4,NULL);
INSERT INTO "elements" VALUES(101,'Iteration','Iteration statements',6,7,NULL);
INSERT INTO "elements" VALUES(102,'ConsoleRW','Read/write specified stream',1,47,NULL);
INSERT INTO "elements" VALUES(103,'*Helpers_scheme','Scheme',16,1,NULL);
INSERT INTO "elements" VALUES(104,'Version','Information about application',16,3,NULL);
INSERT INTO "elements" VALUES(105,'LineBreak','Link break',16,4,NULL);
INSERT INTO "elements" VALUES(106,'LineBreakEx','Enhanced link break',16,5,NULL);
INSERT INTO "elements" VALUES(107,'HubEx','Enhanced Hub',16,6,NULL);
INSERT INTO "elements" VALUES(108,'GetDataEx','Enhanced GetData',16,7,NULL);
INSERT INTO "elements" VALUES(109,'Check','Link check',16,8,NULL);
INSERT INTO "elements" VALUES(110,'PointHint','Point hint',16,9,NULL);
INSERT INTO "elements" VALUES(111,'*Helpers_Design','Design',16,11,NULL);
INSERT INTO "elements" VALUES(112,'InfoTip','Info tip',16,12,NULL);
INSERT INTO "elements" VALUES(113,'ViewSHA','View SHA scheme',16,13,NULL);
INSERT INTO "elements" VALUES(114,'PictureTip','Picture tip',16,14,NULL);
INSERT INTO "elements" VALUES(115,'LinkTip','Link tip',16,15,NULL);
INSERT INTO "elements" VALUES(116,'ImageMulti','Container of images',16,16,NULL);
INSERT INTO "elements" VALUES(117,'Shape','Shape',16,17,NULL);
INSERT INTO "elements" VALUES(118,'*Helpers_environment','Environment',16,18,NULL);
INSERT INTO "elements" VALUES(119,'SDKBtn','Button',16,19,NULL);
INSERT INTO "elements" VALUES(120,'ScriptEvents','Script events',16,20,NULL);
INSERT INTO "elements" VALUES(121,'AccessFTP','FTP access',16,21,NULL);
INSERT INTO "elements" VALUES(122,'EncodingConvert','Converts from one encoding to another',1,33,NULL);
INSERT INTO "elements" VALUES(123,'ArrayRW','Read/Write the specified array',12,19,NULL);
INSERT INTO "elements" VALUES(124,'WebClient','Web client',9,23,NULL);
INSERT INTO "elements" VALUES(125,'INIFile','Provides methods for accessing ini-file',10,52,NULL);
INSERT INTO "elements" VALUES(126,'PictureBox','Picture box control',2,10,NULL);
INSERT INTO "elements" VALUES(127,'ListBox','List box control',2,11,NULL);
INSERT INTO "elements" VALUES(128,'NumericUpDown','Spin box control',2,12,NULL);
INSERT INTO "elements" VALUES(129,'AssemblyInfo','Information about application',16,2,NULL);
INSERT INTO "elements" VALUES(130,'LinkLabel','Hyperlinks label control',2,13,NULL);
INSERT INTO "elements" VALUES(131,'DateTimePicker','DateTime picker control',2,14,NULL);
INSERT INTO "elements" VALUES(132,'MonthCalendar','Calendar control',2,15,NULL);
INSERT INTO "elements" VALUES(133,'ToolTipIcon','ToolTip standardized icons',11,5,NULL);
INSERT INTO "elements" VALUES(134,'NotifyIcon','Notify icon component',13,8,NULL);
INSERT INTO "elements" VALUES(135,'Inline','Inserts the target code',8,4,NULL);
INSERT INTO "elements" VALUES(136,'*Dialogs','Dialog controls',2,92,NULL);
INSERT INTO "elements" VALUES(137,'*Main','Main controls',2,1,NULL);
INSERT INTO "elements" VALUES(138,'OpenFileDialog','Opens file dialog',2,98,NULL);
INSERT INTO "elements" VALUES(139,'SDialog','Save file dialog',1,20,NULL);
INSERT INTO "elements" VALUES(140,'FolderBrowserDialog','Prompts to select a folder',2,100,NULL);
INSERT INTO "elements" VALUES(141,'FontDialog','Font dialog',2,101,NULL);
INSERT INTO "elements" VALUES(142,'ColorDialog','Color dialog',2,102,NULL);
INSERT INTO "elements" VALUES(143,'GetData','Vertical Hub',4,4,NULL);
INSERT INTO "elements" VALUES(144,'EventLog','Windows event logs',14,63,NULL);
INSERT INTO "elements" VALUES(145,'EventLogEntryType','Log entry type',14,65,NULL);
INSERT INTO "elements" VALUES(146,'*Registry','Windows Registry',14,37,NULL);
INSERT INTO "elements" VALUES(147,'Registry','Windows Registry read/write',14,38,NULL);
INSERT INTO "elements" VALUES(148,'DLL','Library',1,4,NULL);
INSERT INTO "elements" VALUES(149,'Using','Adds namespace',8,5,NULL);
INSERT INTO "elements" VALUES(150,'RegistryKeyOpen','Opens the registry key',1,39,NULL);
INSERT INTO "elements" VALUES(151,'*Environment','Environment',14,1,NULL);
INSERT INTO "elements" VALUES(152,'RegistryKeyRW','Read/Write the registry key',1,40,NULL);
INSERT INTO "elements" VALUES(153,'RegistryKeyTools','Registry key tools',1,41,NULL);
INSERT INTO "elements" VALUES(154,'RegistryKeyAC','Registry key access control',1,42,NULL);
INSERT INTO "elements" VALUES(155,'*StringBuilder','String builder',1,23,NULL);
INSERT INTO "elements" VALUES(156,'StringBuilder','Mutable string of characters',5,19,NULL);
INSERT INTO "elements" VALUES(157,'StringBuilderReplace','Replaces in the StringBuilder',1,24,NULL);
INSERT INTO "elements" VALUES(158,'StringBuilderInsert','Inserts into the StringBuilder',1,25,NULL);
INSERT INTO "elements" VALUES(159,'StringBuilderRemove','Removes from the StringBuilder',1,26,NULL);
INSERT INTO "elements" VALUES(160,'StringBuilderCopy','Copies from the StringBuilder',1,27,NULL);
INSERT INTO "elements" VALUES(161,'MathParse','Mathematical expressions',6,8,NULL);
INSERT INTO "elements" VALUES(162,'StringBuilderFormat','Appends by format string',1,28,NULL);
INSERT INTO "elements" VALUES(163,'Counter','Sequenced counter',6,9,NULL);
INSERT INTO "elements" VALUES(164,'Case','The switch statement',6,10,NULL);
INSERT INTO "elements" VALUES(165,'EditMultiEx','Editor of MultiElementEx',1,5,NULL);
INSERT INTO "elements" VALUES(166,'MultiElementEx','Container',4,14,NULL);
INSERT INTO "elements" VALUES(167,'*Containers','Containers',2,39,NULL);
INSERT INTO "elements" VALUES(168,'Panel','Collections of controls',1,6,NULL);
INSERT INTO "elements" VALUES(169,'ChildPanel','Container of controls',2,40,NULL);
INSERT INTO "elements" VALUES(170,'GlobalVar','Global variable',4,15,NULL);
INSERT INTO "elements" VALUES(171,'GroupBox','Frame around a group of controls',1,7,NULL);
INSERT INTO "elements" VALUES(172,'ChildGroupBox','Frame around a group of controls',2,41,NULL);
INSERT INTO "elements" VALUES(173,'TabPage','Represents a single tab page in a ChildTabControl',1,8,NULL);
INSERT INTO "elements" VALUES(174,'TabControl','Manages a related set of tab pages',1,9,NULL);
INSERT INTO "elements" VALUES(175,'ChildTabControl','Manages a related set of tab pages',2,42,NULL);
INSERT INTO "elements" VALUES(176,'ChildTabPage','Single tab page in a TabControl',2,43,NULL);
INSERT INTO "elements" VALUES(177,'ControlCollection','Collection of Controls',1,22,NULL);
INSERT INTO "elements" VALUES(178,'FlowLayoutPanel','Flow layout panel',1,10,NULL);
INSERT INTO "elements" VALUES(179,'ChildFlowPanel','Panel controls the dynamic layout',2,44,NULL);
INSERT INTO "elements" VALUES(180,'SplitContainer','Split container',1,11,NULL);
INSERT INTO "elements" VALUES(181,'ChildSplitContainer','Two resizable panels',2,45,NULL);
INSERT INTO "elements" VALUES(182,'SplitterPanel','Splitter panel',1,12,NULL);
INSERT INTO "elements" VALUES(183,'ChildSplitterPanel','Panel of the SplitContainer',2,46,NULL);
INSERT INTO "elements" VALUES(184,'GetIndexData','Data access by index',4,5,NULL);
INSERT INTO "elements" VALUES(185,'RichTextBox','Rich editing control',2,17,NULL);
INSERT INTO "elements" VALUES(186,'Color','Represents an ARGB color',19,84,NULL);
INSERT INTO "elements" VALUES(187,'Try','Try statement',8,6,NULL);
INSERT INTO "elements" VALUES(188,'MT_Add','Adds to MT-array',17,1,NULL);
INSERT INTO "elements" VALUES(189,'MT_Get','Gets from MT-array',17,2,NULL);
INSERT INTO "elements" VALUES(190,'MT_Enum','Enumerates the MT-array',17,3,NULL);
INSERT INTO "elements" VALUES(191,'MT_Split','Splits the MT-array',17,4,NULL);
INSERT INTO "elements" VALUES(192,'StringSplit','Split string',5,14,NULL);
INSERT INTO "elements" VALUES(193,'Debug','Internal debugger',16,31,NULL);
INSERT INTO "elements" VALUES(194,'MemoryStream','Stores the binary stream to memory',10,43,NULL);
INSERT INTO "elements" VALUES(195,'EventFromData','Generates an event when accessing data',4,16,NULL);
INSERT INTO "elements" VALUES(196,'Rectangle','Represent Rectangle structure',19,90,NULL);
INSERT INTO "elements" VALUES(197,'Point','Represent Point structure',19,86,NULL);
INSERT INTO "elements" VALUES(198,'Size','Represent Size structure',19,88,NULL);
INSERT INTO "elements" VALUES(199,'*Photoshop','Photoshop',18,11,NULL);
INSERT INTO "elements" VALUES(200,'PsApplication','Photoshop application',18,12,NULL);
INSERT INTO "elements" VALUES(201,'PsDocumentNew','Creates new document',18,14,NULL);
INSERT INTO "elements" VALUES(202,'PsDocOpen','Opens a document',18,15,NULL);
INSERT INTO "elements" VALUES(203,'PsDocSave','Saves a document',18,16,NULL);
INSERT INTO "elements" VALUES(204,'PsDocument','Photoshop document',18,18,NULL);
INSERT INTO "elements" VALUES(205,'PsAction','Plays an action',18,19,NULL);
INSERT INTO "elements" VALUES(206,'PsDoJavaScript','Executes the script',18,20,NULL);
INSERT INTO "elements" VALUES(207,'*Options','Other options',18,31,NULL);
INSERT INTO "elements" VALUES(208,'PsBitmapConversionOptions','Convertion options',18,33,NULL);
INSERT INTO "elements" VALUES(209,'PsIndexedConversionOptions','Convertion options',18,34,NULL);
INSERT INTO "elements" VALUES(210,'*OpenOptions','Open options',18,36,NULL);
INSERT INTO "elements" VALUES(211,'PsRAWOpenOptions','Camera RAW open options',18,37,NULL);
INSERT INTO "elements" VALUES(212,'PsRAWFormatOpenOptions','RAW format open options',18,38,NULL);
INSERT INTO "elements" VALUES(213,'PsPDFOpenOptions','PDF open options',18,39,NULL);
INSERT INTO "elements" VALUES(214,'PsEPSOpenOptions','EPS open options',18,40,NULL);
INSERT INTO "elements" VALUES(215,'*SaveOptions','Save options',18,41,NULL);
INSERT INTO "elements" VALUES(216,'PsJPEGSaveOptions','JPEG save options',18,45,NULL);
INSERT INTO "elements" VALUES(217,'PsSaveOptions','Photoshop save options',18,48,NULL);
INSERT INTO "elements" VALUES(218,'PsPNGSaveOptions','PNG save options',18,47,NULL);
INSERT INTO "elements" VALUES(219,'PsGIFSaveOptions','GIF save options',18,44,NULL);
INSERT INTO "elements" VALUES(220,'PsBMPSaveOptions','BMP save options',18,42,NULL);
INSERT INTO "elements" VALUES(221,'PsTiffSaveOptions','TIFF save options',18,49,NULL);
INSERT INTO "elements" VALUES(222,'PsEPSSaveOptions','EPS save options',18,43,NULL);
INSERT INTO "elements" VALUES(223,'*Indesign','Indesign',18,60,NULL);
INSERT INTO "elements" VALUES(224,'IdApplication','Indesign application',18,61,NULL);
INSERT INTO "elements" VALUES(225,'IdDocumentNew','Makes a new document',18,62,NULL);
INSERT INTO "elements" VALUES(226,'IdDocOpen','Opens a document',18,63,NULL);
INSERT INTO "elements" VALUES(227,'IdDocSave','Saves a document',18,64,NULL);
INSERT INTO "elements" VALUES(228,'IdDocument','Indesign document',18,65,NULL);
INSERT INTO "elements" VALUES(230,'IdDoScript','Executes the script',18,66,NULL);
INSERT INTO "elements" VALUES(231,'IndesignPreflightProfile','Loads the preflight profile',18,68,NULL);
INSERT INTO "elements" VALUES(232,'IdEventListener','Adds or removes an event listener',18,67,NULL);
INSERT INTO "elements" VALUES(233,'IndesignPreflightProcess','Performs the preflight processing',18,69,NULL);
INSERT INTO "elements" VALUES(234,'IdDocExport','Export to a file',18,70,NULL);
INSERT INTO "elements" VALUES(235,'*Acrobat','Acrobat',18,1,NULL);
INSERT INTO "elements" VALUES(236,'Acrobat','Acrobat application',18,2,NULL);
INSERT INTO "elements" VALUES(237,'AcrobatAVDoc','Creates a view of a document',18,3,NULL);
INSERT INTO "elements" VALUES(238,'AcrobatAVPageView','Manages the page view',18,4,NULL);
INSERT INTO "elements" VALUES(239,'AcrobatPDDoc','PDF document',18,5,NULL);
INSERT INTO "elements" VALUES(241,'AcrobatRect','The rectangle area in the document',18,6,NULL);
INSERT INTO "elements" VALUES(242,'AcrobatSave','Saves a document',18,7,NULL);
INSERT INTO "elements" VALUES(243,'AcrobatInsert','Inserts the pages',18,8,NULL);
INSERT INTO "elements" VALUES(244,'AcrobatReplace','Replaces the pages',18,9,NULL);
INSERT INTO "elements" VALUES(245,'AcrobatExport','Exports a document',18,10,NULL);
INSERT INTO "elements" VALUES(246,'*ODBC','ODBC',7,7,NULL);
INSERT INTO "elements" VALUES(247,'*SQLite','SQLite',7,13,NULL);
INSERT INTO "elements" VALUES(248,'SQLite','Data Base SQLite',7,14,NULL);
INSERT INTO "elements" VALUES(249,'SQLite_data','Get data table',7,15,NULL);
INSERT INTO "elements" VALUES(250,'SQLite_queryscalar','Get a single value',7,16,NULL);
INSERT INTO "elements" VALUES(251,'SQLite_exec','Executes a query',7,17,NULL);
INSERT INTO "elements" VALUES(252,'*DataGrid','DataGrid',2,83,NULL);
INSERT INTO "elements" VALUES(253,'DataGridView','Displays data in a customizable grid',2,84,NULL);
INSERT INTO "elements" VALUES(254,'DataGridView_Edit','Manages the current cell in edit mode',2,85,NULL);
INSERT INTO "elements" VALUES(255,'DataGridView_Cell','Read/Write the cell',2,86,NULL);
INSERT INTO "elements" VALUES(256,'DataGridView_Sort','Sorts the contents',2,88,NULL);
INSERT INTO "elements" VALUES(257,'TagFind','Search for text using start and stop markers',5,15,NULL);
INSERT INTO "elements" VALUES(258,'*Common','Common',9,1,NULL);
INSERT INTO "elements" VALUES(267,'TreeView','TreeView control',2,18,NULL);
INSERT INTO "elements" VALUES(268,'CheckedListBox','CheckedListBox control',2,19,NULL);
INSERT INTO "elements" VALUES(269,'ChildForm','Child form',2,47,NULL);
INSERT INTO "elements" VALUES(270,'Form','Child form',2,48,NULL);
INSERT INTO "elements" VALUES(271,'FolderBrowserDialog','Prompts to select a folder',10,4,NULL);
INSERT INTO "elements" VALUES(272,'Array','Array object',12,2,NULL);
INSERT INTO "elements" VALUES(273,'Type','Type declaration',8,7,NULL);
INSERT INTO "elements" VALUES(274,'BitConverter','Converts to an array of bytes and to back',1,36,NULL);
INSERT INTO "elements" VALUES(275,'Convert','Converts a base data type to another',8,21,NULL);
INSERT INTO "elements" VALUES(276,'Base64','Converts a Base64 data type',1,35,NULL);
INSERT INTO "elements" VALUES(277,'CultureInfo','Information about a culture',14,22,NULL);
INSERT INTO "elements" VALUES(278,'DateTimeFormatInfo','DateTime values on the culture',14,23,NULL);
INSERT INTO "elements" VALUES(279,'NumberFormatInfo','Numeric on the culture',14,24,NULL);
INSERT INTO "elements" VALUES(280,'GregorianCalendar','Represents the Gregorian calendar',14,10,NULL);
INSERT INTO "elements" VALUES(281,'SecureString','Represents a confidential text',5,16,NULL);
INSERT INTO "elements" VALUES(282,'Encoding','Represents a character encoding',1,30,NULL);
INSERT INTO "elements" VALUES(283,'ProcessStartInfo','Process params',13,2,NULL);
INSERT INTO "elements" VALUES(284,'*Encoding/Decoding','Encoding/Decoding',5,24,NULL);
INSERT INTO "elements" VALUES(285,'DecoderFallback','Failure-handling mechanism',1,31,NULL);
INSERT INTO "elements" VALUES(286,'EncoderFallback','Failure-handling mechanism',1,32,NULL);
INSERT INTO "elements" VALUES(287,'DirectorySecurity','Access control and audit security',10,18,NULL);
INSERT INTO "elements" VALUES(288,'*Security','Security',14,47,NULL);
INSERT INTO "elements" VALUES(289,'NTAccount','Represents a user or group account',14,48,NULL);
INSERT INTO "elements" VALUES(290,'SecurityIdentifier','Represents a SID',14,49,NULL);
INSERT INTO "elements" VALUES(291,'WindowsIdentity','Represents a Windows user',14,50,NULL);
INSERT INTO "elements" VALUES(292,'GenericIdentity','Represents a generic user.',14,51,NULL);
INSERT INTO "elements" VALUES(293,'IdentityReferenceCollection','IdentityReference collection',14,52,NULL);
INSERT INTO "elements" VALUES(294,'WindowsPrincipal','Check Windows group',14,53,NULL);
INSERT INTO "elements" VALUES(295,'GenericPrincipal','Check the specified role',14,54,NULL);
INSERT INTO "elements" VALUES(296,'SerialPort','Represents a serial port resource',13,51,NULL);
INSERT INTO "elements" VALUES(297,'Thread','Creates and controls a thread',13,10,NULL);
INSERT INTO "elements" VALUES(298,'*Tools','Tools',19,1,NULL);
INSERT INTO "elements" VALUES(299,'Graphics','Encapsulates a GDI+ drawing surface',19,2,NULL);
INSERT INTO "elements" VALUES(300,'CreateGraphics','Creates a new Graphics',1,48,NULL);
INSERT INTO "elements" VALUES(301,'ImageList','Collection of Image objects',19,23,NULL);
INSERT INTO "elements" VALUES(302,'Bitmap','Encapsulates a GDI+ bitmap',19,24,NULL);
INSERT INTO "elements" VALUES(303,'Icon','Represents a Windows icon',19,25,NULL);
INSERT INTO "elements" VALUES(304,'Metafile','Defines a graphic metafile',19,33,NULL);
INSERT INTO "elements" VALUES(305,'Pen','Defines an object used to draw lines and curves',19,8,NULL);
INSERT INTO "elements" VALUES(306,'SolidBrush','Defines a brush of a single color',19,9,NULL);
INSERT INTO "elements" VALUES(307,'TextureBrush','Defines a texture brush',19,10,NULL);
INSERT INTO "elements" VALUES(308,'GraphicsContainer','Manages the graphics container',19,4,NULL);
INSERT INTO "elements" VALUES(309,'*Draw','Draw',19,38,NULL);
INSERT INTO "elements" VALUES(310,'DrawIcon','Draws the Icon',19,40,NULL);
INSERT INTO "elements" VALUES(311,'DrawImage','Draws the image',19,39,NULL);
INSERT INTO "elements" VALUES(312,'DrawLine','Draws a line',19,41,NULL);
INSERT INTO "elements" VALUES(313,'DrawArc','Draws an arc',19,42,NULL);
INSERT INTO "elements" VALUES(314,'DrawBezier','Draws a Bezier spline',19,43,NULL);
INSERT INTO "elements" VALUES(315,'DrawEllipse','Draws an ellipse',19,44,NULL);
INSERT INTO "elements" VALUES(316,'DrawClosedCurve','Draws a closed cardinal spline',19,45,NULL);
INSERT INTO "elements" VALUES(317,'DrawCurve','Draws a cardinal spline',19,46,NULL);
INSERT INTO "elements" VALUES(318,'DrawPath','Draws a GraphicsPath',19,47,NULL);
INSERT INTO "elements" VALUES(319,'DrawPie','Draws a pie shape',19,48,NULL);
INSERT INTO "elements" VALUES(320,'DrawPolygon','Draws a polygon',19,49,NULL);
INSERT INTO "elements" VALUES(321,'DrawRectangle','Draws a rectangle',19,50,NULL);
INSERT INTO "elements" VALUES(322,'DrawString','Draws the specified text string',19,51,NULL);
INSERT INTO "elements" VALUES(323,'*Fill','Fill',19,53,NULL);
INSERT INTO "elements" VALUES(324,'FillClosedCurve','Fills a closed cardinal spline',19,54,NULL);
INSERT INTO "elements" VALUES(325,'FillEllipse','Fills the interior of an ellipse',19,55,NULL);
INSERT INTO "elements" VALUES(326,'FillPath','Fills the interior of a GraphicsPath',19,56,NULL);
INSERT INTO "elements" VALUES(327,'FillPie','Fills the interior of a pie section',19,57,NULL);
INSERT INTO "elements" VALUES(328,'FillPolygon','Fills the interior of a polygon',19,58,NULL);
INSERT INTO "elements" VALUES(329,'FillRectangle','Fills the interior of a rectangle',19,59,NULL);
INSERT INTO "elements" VALUES(330,'FillRegion','Fills the interior of a Region',19,60,NULL);
INSERT INTO "elements" VALUES(331,'*Transform','Transform',19,70,NULL);
INSERT INTO "elements" VALUES(332,'TranslateTransform','Changes the coordinate system',19,71,NULL);
INSERT INTO "elements" VALUES(333,'MultiplyTransform','Multiplies the world',19,74,NULL);
INSERT INTO "elements" VALUES(334,'ScaleTransform','Applies the specified scaling',19,72,NULL);
INSERT INTO "elements" VALUES(335,'RotateTransform','Applies the specified rotation',19,73,NULL);
INSERT INTO "elements" VALUES(336,'CopyFromScreen','Copy from the screen to the Graphics',19,75,NULL);
INSERT INTO "elements" VALUES(337,'Screen','Represents a display device',14,11,NULL);
INSERT INTO "elements" VALUES(338,'ExcludeClip','Exclude the specified area',19,76,NULL);
INSERT INTO "elements" VALUES(339,'IntersectClip','Intersection the specified area',19,77,NULL);
INSERT INTO "elements" VALUES(340,'GraphicsState','Manages the state of a Graphics',19,3,NULL);
INSERT INTO "elements" VALUES(341,'StringFormat','Encapsulates text layout information',19,67,NULL);
INSERT INTO "elements" VALUES(342,'MeasureString','Measures the specified string',19,66,NULL);
INSERT INTO "elements" VALUES(343,'*Structures','Structures',19,83,NULL);
INSERT INTO "elements" VALUES(344,'SizeF','Represent SizeF structure',19,89,NULL);
INSERT INTO "elements" VALUES(345,'PointF','Represents PointF structure',19,87,NULL);
INSERT INTO "elements" VALUES(346,'RectangleF','Represents RectangleF structure',19,91,NULL);
INSERT INTO "elements" VALUES(347,'Matrix','Encapsulates a 3x3 affine matrix',19,78,NULL);
INSERT INTO "elements" VALUES(348,'ColorPalette','Represents a color palette control',2,21,NULL);
INSERT INTO "elements" VALUES(349,'SmtpClient','Send e-mail by using the SMTP',9,54,NULL);
INSERT INTO "elements" VALUES(350,'MailMessage','Represents an e-mail message',9,7,NULL);
INSERT INTO "elements" VALUES(351,'Attachment','Represents an attachment to an e-mail',9,8,NULL);
INSERT INTO "elements" VALUES(352,'ContentType','Represents Content-Type header',9,9,NULL);
INSERT INTO "elements" VALUES(353,'MailAddress','Represents an e-mail address',9,11,NULL);
INSERT INTO "elements" VALUES(354,'NetworkCredential','Password-based authentication',9,12,NULL);
INSERT INTO "elements" VALUES(355,'TCP_Client','Provides TCP client',9,5,NULL);
INSERT INTO "elements" VALUES(356,'MaskedTextBox','Masked text box control',2,16,NULL);
INSERT INTO "elements" VALUES(357,'MessageBox','Displays a message box',2,93,NULL);
INSERT INTO "elements" VALUES(358,'ControlMethods','Represents methods of Control',2,60,NULL);
INSERT INTO "elements" VALUES(359,'Font','Particular format for text',19,64,NULL);
INSERT INTO "elements" VALUES(360,'Cursor','Represents the mouse pointer',19,16,NULL);
INSERT INTO "elements" VALUES(361,'OdbcConnection','Open connection to a data source',7,8,NULL);
INSERT INTO "elements" VALUES(362,'OdbcConnectionStringBuilder','Create connection strings',7,9,NULL);
INSERT INTO "elements" VALUES(363,'OdbcDataAdapter','Represents a set of data',7,10,NULL);
INSERT INTO "elements" VALUES(364,'OdbcCommand','Represents an SQL statement',7,11,NULL);
INSERT INTO "elements" VALUES(365,'OdbcCommandBuilder','Autogenerates single-table commands',7,12,NULL);
INSERT INTO "elements" VALUES(366,'ToolTip','Displays a brief description of a control''s',13,9,NULL);
INSERT INTO "elements" VALUES(367,'*MySQL','MySQL',7,18,NULL);
INSERT INTO "elements" VALUES(368,'MySqlConnection','Connection to a MySQL Server',7,19,NULL);
INSERT INTO "elements" VALUES(369,'MySqlDataAdapter','Represents a set of data',7,20,NULL);
INSERT INTO "elements" VALUES(370,'MySqlConnectionStringBuilder','Create connection strings',7,21,NULL);
INSERT INTO "elements" VALUES(371,'*Common','Common',7,1,NULL);
INSERT INTO "elements" VALUES(372,'ConnectionState','The current state of the connection',7,2,NULL);
INSERT INTO "elements" VALUES(373,'StateChangeEventArgs','The state change event of data provider',7,3,NULL);
INSERT INTO "elements" VALUES(374,'DataSet','Represents an in-memory cache of data',7,4,NULL);
INSERT INTO "elements" VALUES(375,'DataTable','Represents one table of in-memory data',7,5,NULL);
INSERT INTO "elements" VALUES(376,'BindingSource','Encapsulates the data source for a form',7,6,NULL);
INSERT INTO "elements" VALUES(377,'AutoCompleteStringCollection','Collection of auto-completion strings',5,18,NULL);
INSERT INTO "elements" VALUES(378,'Uri','Uniform resource identifier',9,63,NULL);
INSERT INTO "elements" VALUES(379,'EventArgs','Provides data for the event data',2,62,NULL);
INSERT INTO "elements" VALUES(380,'ItemCheckEventArgs','Provides data for the ItemCheck event',2,63,NULL);
INSERT INTO "elements" VALUES(381,'TrackBar','Standard Windows track bar',2,22,NULL);
INSERT INTO "elements" VALUES(382,'TypeValidationEventArgs','Provides data for the TypeValidationCompleted event.',2,64,NULL);
INSERT INTO "elements" VALUES(383,'MaskInputRejectedEventArgs','Provides data for the MaskInputRejected event.',2,65,NULL);
INSERT INTO "elements" VALUES(384,'CancelEventArgs','Provides data for a cancelable event.',2,66,NULL);
INSERT INTO "elements" VALUES(385,'MessageBoxButtons','MessageBox buttons enumeration',2,94,NULL);
INSERT INTO "elements" VALUES(386,'MessageBoxIcon','MessageBox icons enumeration',2,95,NULL);
INSERT INTO "elements" VALUES(387,'Sleep','Suspends the current thread',13,11,NULL);
INSERT INTO "elements" VALUES(388,'DataReceivedEventArgs','Provides data for the console',2,67,NULL);
INSERT INTO "elements" VALUES(389,'FtpClient','Represents FTP client',9,4,NULL);
INSERT INTO "elements" VALUES(390,'FtpStatusCode','Status codes of a FTP operation',1,37,NULL);
INSERT INTO "elements" VALUES(391,'SaveFileDialog','Save file dialog',2,99,NULL);
INSERT INTO "elements" VALUES(392,'SaveFileDialog','Save file dialog',10,3,NULL);
INSERT INTO "elements" VALUES(393,'SystemFonts','Represents system fonts',14,12,NULL);
INSERT INTO "elements" VALUES(394,'DataGridViewDataErrorContexts','The state of a data-bound DataGridView',2,90,NULL);
INSERT INTO "elements" VALUES(395,'IList','Collection of objects Interface',20,1,NULL);
INSERT INTO "elements" VALUES(396,'*Other','Satellites of controls',2,59,NULL);
INSERT INTO "elements" VALUES(397,'ICloneable','Creates a new instance of a class',20,2,NULL);
INSERT INTO "elements" VALUES(398,'Stack_T','LIFO stack with arbitrary type',4,11,NULL);
INSERT INTO "elements" VALUES(399,'Queue_T','FIFO queue with arbitrary type',4,12,NULL);
INSERT INTO "elements" VALUES(400,'FileAttributes','Attributes for files and directories',10,93,NULL);
INSERT INTO "elements" VALUES(401,'LogicalOperator','Logical operations',6,11,NULL);
INSERT INTO "elements" VALUES(402,'ImplementDelegate','Makes delegate',4,17,NULL);
INSERT INTO "elements" VALUES(403,'TimerThread','Interval timer on new thread',13,13,NULL);
INSERT INTO "elements" VALUES(404,'KeyEventArgs','Provides data for the KeyDown or KeyUp event',2,68,NULL);
INSERT INTO "elements" VALUES(405,'KeyPressEventArgs','Provides data for the KeyPress event',2,70,NULL);
INSERT INTO "elements" VALUES(406,'Keys','Specifies key codes and modifiers',11,10,NULL);
INSERT INTO "elements" VALUES(407,'RegexOptions','Regular expression options',5,42,NULL);
INSERT INTO "elements" VALUES(408,'REMatchSynchronized','Represents the Match shared between multiple threads',5,40,NULL);
INSERT INTO "elements" VALUES(409,'Regex','Represents an immutable regular expression',5,41,NULL);
INSERT INTO "elements" VALUES(410,'Stopwatch','Measure elapsed time',13,12,NULL);
INSERT INTO "elements" VALUES(411,'ASCIIEncoding','ASCII character encoding',5,25,NULL);
INSERT INTO "elements" VALUES(412,'UnicodeEncoding','UTF-16 encoding',5,26,NULL);
INSERT INTO "elements" VALUES(413,'UTF32Encoding','UTF-32 encoding',5,27,NULL);
INSERT INTO "elements" VALUES(414,'UTF7Encoding','UTF-7 encoding',5,28,NULL);
INSERT INTO "elements" VALUES(415,'UTF8Encoding','UTF-8 encoding',5,29,NULL);
INSERT INTO "elements" VALUES(416,'EncoderExceptionFallback','Throws EncoderFallbackException',5,30,NULL);
INSERT INTO "elements" VALUES(417,'DecoderExceptionFallback','Throws DecoderFallbackException',5,31,NULL);
INSERT INTO "elements" VALUES(418,'DecoderReplacementFallback','Replaces string instead of a decoded input byte sequence',5,32,NULL);
INSERT INTO "elements" VALUES(419,'EncoderReplacementFallback','Replaces string instead of the original input character',5,33,NULL);
INSERT INTO "elements" VALUES(420,'EncodingInfo','Information about an encoding',5,34,NULL);
INSERT INTO "elements" VALUES(421,'MathPow','Number raise to the power',3,2,NULL);
INSERT INTO "elements" VALUES(422,'MathAbs','Absolute value of a number',3,3,NULL);
INSERT INTO "elements" VALUES(423,'MathCeiling','Smallest integer',3,4,NULL);
INSERT INTO "elements" VALUES(424,'MathBigMul','Product of two 32-bit numbers',3,5,NULL);
INSERT INTO "elements" VALUES(425,'MathDivRem','Quotient of two numbers',3,6,NULL);
INSERT INTO "elements" VALUES(426,'MathFloor','Largest integer',3,7,NULL);
INSERT INTO "elements" VALUES(427,'MathMax','Larger of two numbers',3,8,NULL);
INSERT INTO "elements" VALUES(428,'MathMin','Smaller of two numbers',3,9,NULL);
INSERT INTO "elements" VALUES(429,'MathIEEERemainder','Remainder resulting from the division',3,10,NULL);
INSERT INTO "elements" VALUES(430,'MathRound','Nearest integer of the number',3,11,NULL);
INSERT INTO "elements" VALUES(431,'MathSign','Sign of the number',3,12,NULL);
INSERT INTO "elements" VALUES(432,'MathSqrt','Square root of the number',3,13,NULL);
INSERT INTO "elements" VALUES(433,'MathTruncate','Calculates the integral part of a number',3,14,NULL);
INSERT INTO "elements" VALUES(434,'MathLog','Logarithm of a number',3,15,NULL);
INSERT INTO "elements" VALUES(435,'MathLn','Natural logarithm of a number',3,16,NULL);
INSERT INTO "elements" VALUES(436,'MathLg','Base 10 logarithm of a number',3,17,NULL);
INSERT INTO "elements" VALUES(437,'MathExp','E raised to the power',3,18,NULL);
INSERT INTO "elements" VALUES(438,'*Main','Main logic',6,1,NULL);
INSERT INTO "elements" VALUES(439,'*Math','Math functions',3,1,NULL);
INSERT INTO "elements" VALUES(440,'MathTrigonometric','Trigonometric functions',3,19,NULL);
INSERT INTO "elements" VALUES(441,'Conditional','Check the condition',6,12,NULL);
INSERT INTO "elements" VALUES(442,'*OleDb','OleDb',7,22,NULL);
INSERT INTO "elements" VALUES(443,'OleDbConnection','Connection to a data source',7,23,NULL);
INSERT INTO "elements" VALUES(444,'OleDbDataAdapter','Represents a set of data',7,24,NULL);
INSERT INTO "elements" VALUES(445,'OleDbConnectionStringBuilder','Create connection strings',7,25,NULL);
INSERT INTO "elements" VALUES(446,'OleDbCommandBuilder','Autogenerates single-table commands',7,26,NULL);
INSERT INTO "elements" VALUES(447,'*SqlServer','SqlServer',7,27,NULL);
INSERT INTO "elements" VALUES(448,'SqlConnection','Connection to a SQL Server',7,28,NULL);
INSERT INTO "elements" VALUES(449,'SqlDataAdapter','Represents a set of data',7,29,NULL);
INSERT INTO "elements" VALUES(450,'SqlConnectionStringBuilder','Create connection strings',7,30,NULL);
INSERT INTO "elements" VALUES(451,'SqlCommandBuilder','Autogenerates single-table commands',7,31,NULL);
INSERT INTO "elements" VALUES(452,'*Oracle','Oracle',7,32,NULL);
INSERT INTO "elements" VALUES(453,'OracleConnection','Connection to a Oracle',7,33,NULL);
INSERT INTO "elements" VALUES(454,'OracleDataAdapter','Represents a set of data',7,34,NULL);
INSERT INTO "elements" VALUES(455,'OracleConnectionStringBuilder','Create connection strings',7,35,NULL);
INSERT INTO "elements" VALUES(456,'OracleCommandBuilder','Autogenerates single-table commands',7,36,NULL);
INSERT INTO "elements" VALUES(457,'Boolean','Represents a Boolean value',11,12,NULL);
INSERT INTO "elements" VALUES(458,'IComparable','Comparable interface',20,3,NULL);
INSERT INTO "elements" VALUES(459,'IConvertible','Convertible interface',20,4,NULL);
INSERT INTO "elements" VALUES(460,'*Complex mathematic','Complex mathematic',3,20,NULL);
INSERT INTO "elements" VALUES(461,'Complex','Represents a complex number',3,21,NULL);
INSERT INTO "elements" VALUES(462,'ComplexFromPolar','Complex from polar coordinates',3,22,NULL);
INSERT INTO "elements" VALUES(463,'ComplexOperators','Operations with a complex numbers',3,23,NULL);
INSERT INTO "elements" VALUES(464,'ComplexMultiply','Product of two complex numbers',3,24,NULL);
INSERT INTO "elements" VALUES(465,'ComplexDivide','Divides one complex number by another',3,25,NULL);
INSERT INTO "elements" VALUES(466,'ComplexAdd','Adds two complex numbers',3,26,NULL);
INSERT INTO "elements" VALUES(467,'ComplexSubtract','Subtracts one complex number from another',3,27,NULL);
INSERT INTO "elements" VALUES(468,'ComplexAbs','Absolute value of a complex number',3,28,NULL);
INSERT INTO "elements" VALUES(469,'ComplexConjugate','Conjugate of a complex number',3,29,NULL);
INSERT INTO "elements" VALUES(470,'ComplexExp','E raised to the power by a complex number',3,30,NULL);
INSERT INTO "elements" VALUES(471,'ComplexNegate','Additive inverse of a complex number',3,31,NULL);
INSERT INTO "elements" VALUES(472,'ComplexReciprocal','Multiplicative inverse of a complex number',3,32,NULL);
INSERT INTO "elements" VALUES(473,'ComplexLog10','Base-10 logarithm of a complex number',3,33,NULL);
INSERT INTO "elements" VALUES(474,'ComplexLn','Natural logarithm of a complex number',3,34,NULL);
INSERT INTO "elements" VALUES(475,'ComplexLog','Logarithm of a complex number in a base',3,35,NULL);
INSERT INTO "elements" VALUES(476,'ComplexPower','Complex number raised to a power by a complex number',3,36,NULL);
INSERT INTO "elements" VALUES(477,'ComplexPow','Complex number raised to a power by a number',3,37,NULL);
INSERT INTO "elements" VALUES(478,'ComplexSqrt','Square root of a complex number',3,38,NULL);
INSERT INTO "elements" VALUES(479,'ComplexToString','Complex number to a string',3,39,NULL);
INSERT INTO "elements" VALUES(480,'ComplexTrigonometric','Trigonometric functions of a complex number',3,40,NULL);
INSERT INTO "elements" VALUES(481,'*BigInteger mathematic','BigInteger mathematic',3,41,NULL);
INSERT INTO "elements" VALUES(482,'BigInteger','Arbitrarily large signed integer',3,42,NULL);
INSERT INTO "elements" VALUES(483,'BigIntOperators','Operations with a BigInteger numbers',3,43,NULL);
INSERT INTO "elements" VALUES(484,'BigIntAbs','Absolute value of a BigInteger object',3,44,NULL);
INSERT INTO "elements" VALUES(485,'BigIntAdd','Adds two BigInteger values',3,45,NULL);
INSERT INTO "elements" VALUES(486,'BigIntCompare','Compares two BigInteger values',3,46,NULL);
INSERT INTO "elements" VALUES(487,'ForTyped','Typed loop with condition',6,13,NULL);
INSERT INTO "elements" VALUES(488,'NumberStyles','Style of number',11,13,NULL);
INSERT INTO "elements" VALUES(489,'BigIntParse','Converts a string to BigInteger',3,47,NULL);
INSERT INTO "elements" VALUES(490,'BigIntDivide','Divides one BigInteger value by another',3,48,NULL);
INSERT INTO "elements" VALUES(491,'BigIntDivRem','Quotient and remainder of the division',3,49,NULL);
INSERT INTO "elements" VALUES(492,'BigIntGCDivisor','Greatest common divisor of two BigInteger',3,50,NULL);
INSERT INTO "elements" VALUES(493,'BigIntLog10','Base-10 logarithm of a BigInteger value',3,51,NULL);
INSERT INTO "elements" VALUES(494,'BigIntLog','Logarithm of a BigInteger value',3,52,NULL);
INSERT INTO "elements" VALUES(495,'BigIntLn','Natural logarithm of a BigInteger value',3,53,NULL);
INSERT INTO "elements" VALUES(496,'BigIntMax','Returns the larger of two BigInteger values',3,54,NULL);
INSERT INTO "elements" VALUES(497,'BigIntMin','Returns the smaller of two BigInteger values',3,55,NULL);
INSERT INTO "elements" VALUES(498,'BigIntModPow','Performs modulus division and raised to the power',3,56,NULL);
INSERT INTO "elements" VALUES(499,'BigIntMultiply','Returns the product of two BigInteger values',3,57,NULL);
INSERT INTO "elements" VALUES(500,'BigIntNegate','Negates a specified BigInteger value',3,58,NULL);
INSERT INTO "elements" VALUES(501,'BigIntPow','Raises a BigInteger value to the power',3,59,NULL);
INSERT INTO "elements" VALUES(502,'BigIntRemainder','Remainder of the division',3,60,NULL);
INSERT INTO "elements" VALUES(503,'BigIntSubtract','Subtracts one BigInteger value from another',3,61,NULL);
INSERT INTO "elements" VALUES(504,'BigIntTryParse','Converts from the string representation',3,62,NULL);
INSERT INTO "elements" VALUES(505,'BigIntToString','Converts to the string representation',3,63,NULL);
INSERT INTO "elements" VALUES(506,'*Array','Array',12,1,NULL);
INSERT INTO "elements" VALUES(507,'ArraySet','Sets the element',12,3,NULL);
INSERT INTO "elements" VALUES(508,'ArrayGet','Gets the value of the element',12,4,NULL);
INSERT INTO "elements" VALUES(509,'*Common','Common',12,13,NULL);
INSERT INTO "elements" VALUES(510,'ICollection','Collections interface',20,5,NULL);
INSERT INTO "elements" VALUES(511,'IEnumerable','Exposes the enumerator',20,6,NULL);
INSERT INTO "elements" VALUES(512,'ArraySearch','Searches a sorted Array',12,5,NULL);
INSERT INTO "elements" VALUES(513,'ArrayClear','Clears a range of elements',12,6,NULL);
INSERT INTO "elements" VALUES(514,'ArrayCopy','Copies a range of elements',12,7,NULL);
INSERT INTO "elements" VALUES(515,'ArrayIndexOf','Index of a value',12,8,NULL);
INSERT INTO "elements" VALUES(516,'ArrayLastIndexOf','Last Index of a value',12,9,NULL);
INSERT INTO "elements" VALUES(517,'ArrayReverse','Reverses the elements',12,10,NULL);
INSERT INTO "elements" VALUES(518,'ArraySort','Sorts the elements',12,11,NULL);
INSERT INTO "elements" VALUES(519,'ArrayInfo','Information about a dimension',12,12,NULL);
INSERT INTO "elements" VALUES(520,'ArrayResize','Resize an array',12,20,NULL);
INSERT INTO "elements" VALUES(521,'ArrayReadOnly','Makes a read-only',12,21,NULL);
INSERT INTO "elements" VALUES(522,'TypeCode','Specifies the type of an object',11,14,NULL);
INSERT INTO "elements" VALUES(523,'*Common','Common',8,1,NULL);
INSERT INTO "elements" VALUES(524,'*Conversion','Conversion',8,20,NULL);
INSERT INTO "elements" VALUES(525,'ChangeType','Converts type to type',8,22,NULL);
INSERT INTO "elements" VALUES(526,'CharArray','Array of chars',12,22,NULL);
INSERT INTO "elements" VALUES(527,'ArrayT','An array of a specified type',12,23,NULL);
INSERT INTO "elements" VALUES(528,'ToBase64CharArray','Converts to a base-64 Unicode array',8,23,NULL);
INSERT INTO "elements" VALUES(529,'FromBase64CharArray','Converts from a base-64 Unicode array',8,24,NULL);
INSERT INTO "elements" VALUES(530,'ToBase64String','Converts to a base-64 string',8,25,NULL);
INSERT INTO "elements" VALUES(531,'FromBase64String','Converts from a base-64 string',8,26,NULL);
INSERT INTO "elements" VALUES(532,'ToBytes','Converts to an array of bytes',8,27,NULL);
INSERT INTO "elements" VALUES(533,'FromBytes','Converts to base data types',8,28,NULL);
INSERT INTO "elements" VALUES(534,'DoubleToInt64','Converts to long',8,29,NULL);
INSERT INTO "elements" VALUES(535,'Int64ToDouble','Converts to double',8,30,NULL);
INSERT INTO "elements" VALUES(536,'ToHexString','Converts to the hex string',8,31,NULL);
INSERT INTO "elements" VALUES(537,'HTTP_Get_Async','HTTP async web request',9,3,NULL);
INSERT INTO "elements" VALUES(538,'*WebClient','WebClient',9,22,NULL);
INSERT INTO "elements" VALUES(539,'WCDownloadData','Downloads a byte array',9,24,NULL);
INSERT INTO "elements" VALUES(540,'WCDownloadDataAsync','Downloads a byte array asynchronously',9,25,NULL);
INSERT INTO "elements" VALUES(541,'DownloadDataCompletedEventArgs','Data event object',9,26,NULL);
INSERT INTO "elements" VALUES(542,'WCDownloadFile','Downloads to a local file',9,27,NULL);
INSERT INTO "elements" VALUES(543,'WCDownloadFileAsync','Downloads to a local file asynchronously',9,28,NULL);
INSERT INTO "elements" VALUES(544,'AsyncCompletedEventArgs','Data for the event',9,29,NULL);
INSERT INTO "elements" VALUES(545,'WCDownloadString','Downloads a string',9,30,NULL);
INSERT INTO "elements" VALUES(546,'WCDownloadStringAsync','Downloads a string asynchronously',9,31,NULL);
INSERT INTO "elements" VALUES(547,'DownloadStringCompletedEventArgs','Data event object',9,32,NULL);
INSERT INTO "elements" VALUES(548,'WCUploadData','Uploads a byte array',9,33,NULL);
INSERT INTO "elements" VALUES(549,'WCUploadDataAsync','Uploads a byte array asynchronously',9,34,NULL);
INSERT INTO "elements" VALUES(550,'UploadDataCompletedEventArgs','Data for the event',9,35,NULL);
INSERT INTO "elements" VALUES(551,'WCUploadFile','Uploads a local file',9,36,NULL);
INSERT INTO "elements" VALUES(552,'WCUploadFileAsync','Uploads a local file asynchronously',9,37,NULL);
INSERT INTO "elements" VALUES(553,'UploadFileCompletedEventArgs','Data event object',9,38,NULL);
INSERT INTO "elements" VALUES(554,'WCUploadString','Uploads a string',9,39,NULL);
INSERT INTO "elements" VALUES(555,'WCUploadStringAsync','Uploads a string asynchronously',9,40,NULL);
INSERT INTO "elements" VALUES(556,'UploadStringCompletedEventArgs','Data for the event',9,41,NULL);
INSERT INTO "elements" VALUES(557,'WCUploadValues','Uploads a name/value collection',9,42,NULL);
INSERT INTO "elements" VALUES(558,'WCUploadValuesAsync','Uploads a name/value collection asynchronously',9,43,NULL);
INSERT INTO "elements" VALUES(559,'UploadValuesCompletedEventArgs','Data for the event',9,44,NULL);
INSERT INTO "elements" VALUES(560,'DownloadProgressChangedEventArgs','Data event object',9,45,NULL);
INSERT INTO "elements" VALUES(561,'UploadProgressChangedEventArgs','Data event object',9,46,NULL);
INSERT INTO "elements" VALUES(562,'WCOpenRead','Opens a stream from a resource',9,47,NULL);
INSERT INTO "elements" VALUES(563,'WCOpenReadAsync','Opens a stream from a resource asynchronously',9,48,NULL);
INSERT INTO "elements" VALUES(564,'OpenReadCompletedEventArgs','Data event object',9,49,NULL);
INSERT INTO "elements" VALUES(565,'WCOpenWrite','Opens a stream for writing',9,50,NULL);
INSERT INTO "elements" VALUES(566,'WCOpenWriteAsync','Opens a stream for writing asynchronously',9,51,NULL);
INSERT INTO "elements" VALUES(567,'OpenWriteCompletedEventArgs','Data event object',9,52,NULL);
INSERT INTO "elements" VALUES(568,'NameValueCollection','Represents a name/value collection',12,24,NULL);
INSERT INTO "elements" VALUES(569,'StreamToString','Converts the stream to the string.',8,32,NULL);
INSERT INTO "elements" VALUES(570,'StringToStream','Converts the string to the stream.',8,33,NULL);
INSERT INTO "elements" VALUES(571,'*SmtpClient','SmtpClient',9,53,NULL);
INSERT INTO "elements" VALUES(572,'SmtpClientSend','Sends an e-mail',9,55,NULL);
INSERT INTO "elements" VALUES(573,'SmtpClientSendAsync','Sends an e-mail asynchronously',9,56,NULL);
INSERT INTO "elements" VALUES(574,'MediaTypeNames','Media type information',9,10,NULL);
INSERT INTO "elements" VALUES(575,'PortScanner','Checks the port',9,6,NULL);
INSERT INTO "elements" VALUES(576,'*MailClient','MailClient',9,57,NULL);
INSERT INTO "elements" VALUES(577,'MailClient','Represents SMTP and IMAP protocols',9,58,NULL);
INSERT INTO "elements" VALUES(578,'MailClientMessages','Messages collection',9,59,NULL);
INSERT INTO "elements" VALUES(579,'MailClientMessage','Info about a message',9,60,NULL);
INSERT INTO "elements" VALUES(580,'MailClientAttachment','Gets an attachment of an e-mail message.',9,61,NULL);
INSERT INTO "elements" VALUES(581,'*Uri','Uri',9,62,NULL);
INSERT INTO "elements" VALUES(582,'UriKind','Kinds of Uris',9,64,NULL);
INSERT INTO "elements" VALUES(583,'UriCheckHostName','Validates DNS name',9,65,NULL);
INSERT INTO "elements" VALUES(584,'UriCheckSchemeName','Validates scheme name',9,66,NULL);
INSERT INTO "elements" VALUES(585,'UriComponents','Parts of a Uri',9,67,NULL);
INSERT INTO "elements" VALUES(586,'UriFormat','Is URI escaped?',9,68,NULL);
INSERT INTO "elements" VALUES(587,'StringComparison','String comparison enum',5,20,NULL);
INSERT INTO "elements" VALUES(588,'UriCompare','Compares URIs',9,69,NULL);
INSERT INTO "elements" VALUES(589,'UriEscape','String to escape',9,70,NULL);
INSERT INTO "elements" VALUES(590,'UriUnescape','String to unescape',9,71,NULL);
INSERT INTO "elements" VALUES(591,'UriFromHex','Hex char to decimal',9,72,NULL);
INSERT INTO "elements" VALUES(592,'*Members','Members',21,1,NULL);
INSERT INTO "elements" VALUES(593,'Constructor','Declares constructor',21,2,NULL);
INSERT INTO "elements" VALUES(594,'Destructor','Declares destructor.',21,3,NULL);
INSERT INTO "elements" VALUES(595,'Const','Declares constant',21,4,NULL);
INSERT INTO "elements" VALUES(596,'Field','Declares field',21,5,NULL);
INSERT INTO "elements" VALUES(597,'Property','Declares property',21,6,NULL);
INSERT INTO "elements" VALUES(598,'Method','Declares method',21,7,NULL);
INSERT INTO "elements" VALUES(599,'Indexer','Declares indexer',21,8,NULL);
INSERT INTO "elements" VALUES(600,'Event','Declares event',21,8,NULL);
INSERT INTO "elements" VALUES(601,'*MembersAccess','MembersAccess',21,10,NULL);
INSERT INTO "elements" VALUES(602,'FieldRW','Field access',21,11,NULL);
INSERT INTO "elements" VALUES(603,'PropertyRW','Property access',21,12,NULL);
INSERT INTO "elements" VALUES(604,'IndexerRW','Indexer access',21,13,NULL);
INSERT INTO "elements" VALUES(605,'DoMethod','Method invoke',21,14,NULL);
INSERT INTO "elements" VALUES(606,'MouseEventArgs','Data for Mouse events',2,71,NULL);
INSERT INTO "elements" VALUES(607,'UriHexEscape','Hex char to escape',9,73,NULL);
INSERT INTO "elements" VALUES(608,'UriHexUnescape','Unescape to hex character',9,74,NULL);
INSERT INTO "elements" VALUES(609,'UriIsHexDigit','Checks hex digit',9,75,NULL);
INSERT INTO "elements" VALUES(610,'UriIsHexEncoding','Checks hex encoding',9,76,NULL);
INSERT INTO "elements" VALUES(611,'VScrollBar','Vertical scroll bar',2,23,NULL);
INSERT INTO "elements" VALUES(612,'HScrollBar','Horizontal scroll bar',2,24,NULL);
INSERT INTO "elements" VALUES(613,'ListView','ListView control',2,26,NULL);
INSERT INTO "elements" VALUES(614,'*MenusToolbars','Menus & Toolbars',2,103,NULL);
INSERT INTO "elements" VALUES(615,'MenuStrip','Menu system for a form',2,105,NULL);
INSERT INTO "elements" VALUES(616,'ToolStripItemClickedEventArgs','Data for ItemClicked event',2,76,NULL);
INSERT INTO "elements" VALUES(617,'ContextMenuStrip','Context menu',2,106,NULL);
INSERT INTO "elements" VALUES(618,'ToolStrip','Toolbar objects',2,107,NULL);
INSERT INTO "elements" VALUES(619,'HashAlgorithm','Hash algorithms',22,1,NULL);
INSERT INTO "elements" VALUES(620,'PathPart','Part of the path',10,24,NULL);
INSERT INTO "elements" VALUES(621,'*Bass','Bass elements',23,1,NULL);
INSERT INTO "elements" VALUES(622,'BassNet','Register BASS.NET API license',23,2,NULL);
INSERT INTO "elements" VALUES(623,'Bass_Init','Initializes a Bass Audio Library',23,3,NULL);
INSERT INTO "elements" VALUES(624,'Bass_SetVolume','Sets the output master volume.',23,4,NULL);
INSERT INTO "elements" VALUES(625,'*BassStream','Bass stream',23,5,NULL);
INSERT INTO "elements" VALUES(626,'Bass_StreamCreateFile','Creates a sample stream from file',23,6,NULL);
INSERT INTO "elements" VALUES(627,'Bass_StreamCreateURL','Creates a sample stream from URL',23,7,NULL);
INSERT INTO "elements" VALUES(628,'*BassChannel','Bass channel',23,8,NULL);
INSERT INTO "elements" VALUES(629,'Bass_ChannelPlay','Creates a stream from file',23,9,NULL);
INSERT INTO "elements" VALUES(630,'Bass_ChannelPause','Pauses a stream',23,10,NULL);
INSERT INTO "elements" VALUES(631,'Bass_ChannelStop','Stops a stream',23,11,NULL);
INSERT INTO "elements" VALUES(632,'Bass_ChannelGetPosition','Gets the playback position',23,12,NULL);
INSERT INTO "elements" VALUES(633,'*BassRecord','Bass record',23,13,NULL);
INSERT INTO "elements" VALUES(634,'*BassFX','Bass FX',23,14,NULL);
INSERT INTO "elements" VALUES(635,'*BassEnum','Bass enumerations',23,15,NULL);
INSERT INTO "elements" VALUES(636,'BASSInit','Initialization flags',23,16,NULL);
INSERT INTO "elements" VALUES(637,'BASSMode','Position mode flags',23,17,NULL);
INSERT INTO "elements" VALUES(638,'BASSFlag_Sample','Sample create flags',23,18,NULL);
INSERT INTO "elements" VALUES(639,'BASSFlag_Stream','Stream flags',23,19,NULL);
INSERT INTO "elements" VALUES(640,'*DirectoryTools','Directory tools',10,10,NULL);
INSERT INTO "elements" VALUES(641,'DirectoryTools','Managing directories',10,12,NULL);
INSERT INTO "elements" VALUES(642,'DirectoryGet','Gets the names of the items in a specified path',10,13,NULL);
INSERT INTO "elements" VALUES(643,'DirectoryEnum','Enumerating the contents of directory',10,14,NULL);
INSERT INTO "elements" VALUES(644,'DirectoryTime','Gets and sets the date and time of a directory path.',10,15,NULL);
INSERT INTO "elements" VALUES(645,'DirectoryACL','Access control list for a directory',10,16,NULL);
INSERT INTO "elements" VALUES(646,'*PathTools','Path tools',10,22,NULL);
INSERT INTO "elements" VALUES(647,'PathCombine','Combines strings into a path',10,25,NULL);
INSERT INTO "elements" VALUES(648,'SearchOption','Search options',10,94,NULL);
INSERT INTO "elements" VALUES(649,'AccessControlSections','Sections of a security descriptor',10,95,NULL);
INSERT INTO "elements" VALUES(650,'FileAppend','Appends the data to the file',10,35,NULL);
INSERT INTO "elements" VALUES(651,'StreamReader','Reading characters from a stream',10,45,NULL);
INSERT INTO "elements" VALUES(652,'StreamReaderMethods','Implements StreamReader`s methods',10,46,NULL);
INSERT INTO "elements" VALUES(653,'StreamWriter','Writing characters to a stream',10,47,NULL);
INSERT INTO "elements" VALUES(654,'StreamWriterMethods','Implements StreamWriter`s methods',10,48,NULL);
INSERT INTO "elements" VALUES(655,'FileInfo','Properties and instance methods',10,49,NULL);
INSERT INTO "elements" VALUES(656,'DirectoryInfo','Properties and instance methods',10,19,NULL);
INSERT INTO "elements" VALUES(657,'FileMode','File open mode',10,87,NULL);
INSERT INTO "elements" VALUES(658,'FileAccess','Access to a file',10,88,NULL);
INSERT INTO "elements" VALUES(659,'FileShare','Kind of access',10,89,NULL);
INSERT INTO "elements" VALUES(660,'FileOptions','Options for creating',10,90,NULL);
INSERT INTO "elements" VALUES(661,'FileCreate','Create file',10,50,NULL);
INSERT INTO "elements" VALUES(662,'EyeOne','Spectrophotometer',24,1,NULL);
INSERT INTO "elements" VALUES(663,'EyeOneMeasure','Measurement from device',24,2,NULL);
INSERT INTO "elements" VALUES(664,'EyeOneColorSpace','Color spaces',24,3,NULL);
INSERT INTO "elements" VALUES(665,'EyeOneIllumination','Illuminations',24,4,NULL);
INSERT INTO "elements" VALUES(666,'EyeOneMeasurementMode','Mode of the measurement',24,5,NULL);
INSERT INTO "elements" VALUES(667,'EyeOneObserver','Angles of the measurement',24,6,NULL);
INSERT INTO "elements" VALUES(668,'EyeOneDensityStandard','Standards of the density measurement',24,7,NULL);
INSERT INTO "elements" VALUES(669,'EyeOneDensityFilter','Filters of the density measurement',24,8,NULL);
INSERT INTO "elements" VALUES(670,'EyeOneWhiteBase','White point calibration',24,9,NULL);
INSERT INTO "elements" VALUES(671,'*DisplayV2','i1 Display V2 options',24,10,NULL);
INSERT INTO "elements" VALUES(672,'EyeOneScreenType','Specify the display type',24,11,NULL);
INSERT INTO "elements" VALUES(673,'EyeOneSubType','Sub type of the device',24,12,NULL);
INSERT INTO "elements" VALUES(674,'EyeOneIntensity','Intensity level of a measurement',24,13,NULL);
INSERT INTO "elements" VALUES(675,'*ColorItems','Color objects',24,14,NULL);
INSERT INTO "elements" VALUES(676,'Lab','Lab value',24,15,NULL);
INSERT INTO "elements" VALUES(677,'Rgb','RGB value',24,16,NULL);
INSERT INTO "elements" VALUES(678,'Cmyk','CMYK value',24,17,NULL);
INSERT INTO "elements" VALUES(679,'dE','Calculates delta-E',24,18,NULL);
INSERT INTO "elements" VALUES(680,'dH','Calculates delta-H',24,19,NULL);
INSERT INTO "elements" VALUES(681,'MessageBoxOptions','Specifies options on a MessageBox',2,97,NULL);
INSERT INTO "elements" VALUES(682,'Help','HTML Help 1.0 engine',13,41,NULL);
INSERT INTO "elements" VALUES(683,'HelpNavigator','Constants of the Help',13,42,NULL);
INSERT INTO "elements" VALUES(684,'MessageBoxDefaultButton','Default button on a MessageBox',2,96,NULL);
INSERT INTO "elements" VALUES(685,'FileSecurity','Access control and audit security',10,51,NULL);
INSERT INTO "elements" VALUES(686,'FileSystemRights','Access rights to use',10,91,NULL);
INSERT INTO "elements" VALUES(687,'SeekOrigin','Points in streams for seeking',10,92,NULL);
INSERT INTO "elements" VALUES(688,'FileStreamMethods','Implements methods of the FileStream',10,41,NULL);
INSERT INTO "elements" VALUES(689,'MemoryStreamMethods','Implements methods of the MemoryStream',10,44,NULL);
INSERT INTO "elements" VALUES(690,'AsyncStreamReader','Reading file asynchronously',10,53,NULL);
INSERT INTO "elements" VALUES(691,'AsyncReadEventArgs','Provides data event on async read',10,54,NULL);
INSERT INTO "elements" VALUES(692,'AsyncStreamWriter','Writing file asynchronously',10,55,NULL);
INSERT INTO "elements" VALUES(693,'AsyncWriteEventArgs','Provides data event on async write',10,56,NULL);
INSERT INTO "elements" VALUES(694,'BinaryReader','Reads binary values',10,57,NULL);
INSERT INTO "elements" VALUES(695,'BinaryWriter','Writes binary values',10,58,NULL);
INSERT INTO "elements" VALUES(696,'StringRemove','Removing a specified part of string',5,4,NULL);
INSERT INTO "elements" VALUES(697,'*Archiving','Stream archiving',10,65,NULL);
INSERT INTO "elements" VALUES(698,'DeflateStream','Compress and decompress streams',10,66,NULL);
INSERT INTO "elements" VALUES(699,'GZipStream','Compress and decompress streams',10,67,NULL);
INSERT INTO "elements" VALUES(700,'GZipStreamMethods','Implements methods of GZipStream',10,68,NULL);
INSERT INTO "elements" VALUES(701,'CompressionMode','Specifies the action to take',10,69,NULL);
INSERT INTO "elements" VALUES(702,'ZipFile','Provides methods for creating, extracting, and opening zip archives.',10,70,NULL);
INSERT INTO "elements" VALUES(703,'ZipArchive','Zip archive format',10,71,NULL);
INSERT INTO "elements" VALUES(704,'ZipArchiveEntry','Zip archive entry',10,72,NULL);
INSERT INTO "elements" VALUES(705,'ZipArchiveMode','Interacting with zip archive entries',10,73,NULL);
INSERT INTO "elements" VALUES(706,'CompressionLevel','Compression level',10,74,NULL);
INSERT INTO "elements" VALUES(707,'ListViewItem','Item in a ListView control',2,72,NULL);
INSERT INTO "elements" VALUES(708,'ZipFileExtensions','Extension methods for the ZipArchive',10,75,NULL);
INSERT INTO "elements" VALUES(709,'*DragDrop','Drag and Drop mechanism',2,108,NULL);
INSERT INTO "elements" VALUES(710,'DragEventArgs','Data for the drag-and-drop events',2,109,NULL);
INSERT INTO "elements" VALUES(711,'DragDropEffects','Effects of a drag-and-drop operation',2,110,NULL);
INSERT INTO "elements" VALUES(712,'IDataObject','Mechanism for transferring data',2,111,NULL);
INSERT INTO "elements" VALUES(713,'DataFormats','Format of data',2,112,NULL);
INSERT INTO "elements" VALUES(714,'*IPC','Interprocess communication',10,76,NULL);
INSERT INTO "elements" VALUES(715,'PipeServer','Reads the data from the PipeClient',10,77,NULL);
INSERT INTO "elements" VALUES(716,'PipeClient','Sends the data to the PipeServer',10,78,NULL);
INSERT INTO "elements" VALUES(717,'MailSlotServer','Reads the text from the MailSlot',10,79,NULL);
INSERT INTO "elements" VALUES(718,'MailSlotClient','Sends the text to the MailSlot',10,80,NULL);
INSERT INTO "elements" VALUES(719,'Mutex','Interprocess synchronization',13,16,NULL);
INSERT INTO "elements" VALUES(720,'ThreadControlAccess','Manage cross-thread control access',8,34,NULL);
INSERT INTO "elements" VALUES(721,'ListViewPrinter','Print an ListView',2,73,NULL);
INSERT INTO "elements" VALUES(722,'*WindowsService','Windows service',13,20,NULL);
INSERT INTO "elements" VALUES(723,'ServiceController','Manage Windows service',13,21,NULL);
INSERT INTO "elements" VALUES(724,'ServiceControllerMethods','Methods of ServiceController',13,22,NULL);
INSERT INTO "elements" VALUES(725,'ServiceControllerStatus','State of the service',13,23,NULL);
INSERT INTO "elements" VALUES(726,'PowerBroadcastStatus','System`s power status',13,24,NULL);
INSERT INTO "elements" VALUES(727,'MyCRC','Calculates CRC16/32',22,2,NULL);
INSERT INTO "elements" VALUES(728,'*EventLog','Windows Event Logs',14,62,NULL);
INSERT INTO "elements" VALUES(729,'EventLogMethods','Implements methods of the EventLog',14,64,NULL);
INSERT INTO "elements" VALUES(730,'*FileEnumeration','FileSystem enumerations',10,86,NULL);
INSERT INTO "elements" VALUES(731,'ControlsFactory','Manipulates with controls',2,74,NULL);
INSERT INTO "elements" VALUES(732,'*FileSystemWatcher','File system monitoring',10,60,NULL);
INSERT INTO "elements" VALUES(733,'WatcherChangeTypes','WatcherChangeTypes enumerations',10,62,NULL);
INSERT INTO "elements" VALUES(734,'FileSystemEventArgs','Data for the directory events',10,63,NULL);
INSERT INTO "elements" VALUES(735,'RenamedEventArgs','Data for the Renamed event',10,64,NULL);
INSERT INTO "elements" VALUES(736,'*BackgroundWorker','BackgroundWorker',13,30,NULL);
INSERT INTO "elements" VALUES(737,'DoWorkEventArgs','Data for the DoWork event',13,32,NULL);
INSERT INTO "elements" VALUES(738,'ProgressChangedEventArgs','Data for the ProgressChanged event',13,33,NULL);
INSERT INTO "elements" VALUES(739,'RunWorkerCompletedEventArgs','Data for the MethodNameCompleted event',13,34,NULL);
INSERT INTO "elements" VALUES(740,'*Help','Help',13,40,NULL);
INSERT INTO "elements" VALUES(741,'*SerialPort','Serial Port',13,50,NULL);
INSERT INTO "elements" VALUES(742,'SerialData','Type of character',13,52,NULL);
INSERT INTO "elements" VALUES(743,'SerialError','Specifies errors',13,53,NULL);
INSERT INTO "elements" VALUES(744,'SerialPinChange','Type of change',13,54,NULL);
INSERT INTO "elements" VALUES(745,'EnvironmentSpecialFolder','Special folders',14,3,NULL);
INSERT INTO "elements" VALUES(746,'EnvironmentSpecialFolderOption','Options of a special folder',14,4,NULL);
INSERT INTO "elements" VALUES(747,'EnvironmentVariableTarget','Location of an environment variable',14,5,NULL);
INSERT INTO "elements" VALUES(748,'*Culture','Culture',14,21,NULL);
INSERT INTO "elements" VALUES(749,'CultureTypes','Types of culture lists',14,25,NULL);
INSERT INTO "elements" VALUES(750,'CultureInfoMethods','Implements methods of the CultureInfo',14,26,NULL);
INSERT INTO "elements" VALUES(751,'IFormatProvider','Control formatting',20,7,NULL);
INSERT INTO "elements" VALUES(752,'DateTimeKind','Kind of DateTime',14,36,NULL);
INSERT INTO "elements" VALUES(753,'IFormattable','Format the value of an object',20,8,NULL);
INSERT INTO "elements" VALUES(754,'RegistryKey','Key-level node',14,39,NULL);
INSERT INTO "elements" VALUES(755,'RegistrySecurity','Security for a registry key',14,40,NULL);
INSERT INTO "elements" VALUES(756,'RegistryHive','Top-level node',14,41,NULL);
INSERT INTO "elements" VALUES(757,'RegistryView','View to target on a 64-bit OS',14,42,NULL);
INSERT INTO "elements" VALUES(758,'RegistryOptions','Options creating a registry key',14,43,NULL);
INSERT INTO "elements" VALUES(759,'RegistryValueKind','Data type of a value',14,44,NULL);
INSERT INTO "elements" VALUES(760,'RegistryKeyPermissionCheck','Security checks accessing',14,45,NULL);
INSERT INTO "elements" VALUES(761,'RegistryRights','Access control rights',14,46,NULL);
INSERT INTO "elements" VALUES(762,'Unsafe','Unsafe block',8,8,NULL);
INSERT INTO "elements" VALUES(763,'IntPtr','Pointer or a handle',8,9,NULL);
INSERT INTO "elements" VALUES(764,'WellKnownSidType','Security identifiers',14,55,NULL);
INSERT INTO "elements" VALUES(765,'WindowsAccountType','Windows account type',14,56,NULL);
INSERT INTO "elements" VALUES(766,'TokenAccessLevels','Access token levels',14,57,NULL);
INSERT INTO "elements" VALUES(767,'IIdentity','Identity interface',20,9,NULL);
INSERT INTO "elements" VALUES(768,'WindowsBuiltInRole','Windows built in roles',14,58,NULL);
INSERT INTO "elements" VALUES(769,'IPrincipal','Principal interface',20,10,NULL);
INSERT INTO "elements" VALUES(770,'ConsoleBounds','Console a properties bounds',15,5,NULL);
INSERT INTO "elements" VALUES(771,'ConsoleColor','Colors for the console',15,6,NULL);
INSERT INTO "elements" VALUES(772,'ConsoleCancelEventArgs','Data for the Console',15,7,NULL);
INSERT INTO "elements" VALUES(773,'ConsoleSpecialKey','Interrupt combinations',15,8,NULL);
INSERT INTO "elements" VALUES(774,'*Debug','Debug',16,30,NULL);
INSERT INTO "elements" VALUES(775,'Debug_','Methods and properties for debug',16,32,NULL);
INSERT INTO "elements" VALUES(776,'Debugger','Communication with a debugger',16,33,NULL);
INSERT INTO "elements" VALUES(777,'BugReport','Bug report information',16,34,NULL);
INSERT INTO "elements" VALUES(778,'MT_Memory','Stores the MT-array',17,5,NULL);
INSERT INTO "elements" VALUES(779,'IDeviceContext','Windows device context',20,11,NULL);
INSERT INTO "elements" VALUES(780,'PaintEventArgs','Data for paint event',2,75,NULL);
INSERT INTO "elements" VALUES(781,'*Images','Images',19,20,NULL);
INSERT INTO "elements" VALUES(782,'ImageFormat','File format of the image',19,26,NULL);
INSERT INTO "elements" VALUES(783,'PixelFormat','Format of the pixel',19,27,NULL);
INSERT INTO "elements" VALUES(784,'GraphicsUnit','Unit of measure',19,17,NULL);
INSERT INTO "elements" VALUES(785,'RotateFlipType','Rotated and flip the image',19,28,NULL);
INSERT INTO "elements" VALUES(786,'Guid','Globally unique identifier',8,10,NULL);
INSERT INTO "elements" VALUES(787,'FrameDimension','Frame dimensions of an image',19,29,NULL);
INSERT INTO "elements" VALUES(788,'PropertyItem','Property of an image',19,30,NULL);
INSERT INTO "elements" VALUES(789,'BitmapData','Attributes of a bitmap image',19,31,NULL);
INSERT INTO "elements" VALUES(790,'ImageLockMode','Locks a portion of an image',19,32,NULL);
INSERT INTO "elements" VALUES(791,'EmfType','Type of an Enhanced Metafile file',19,34,NULL);
INSERT INTO "elements" VALUES(792,'MetafileFrameUnit','Unit of measurement',19,35,NULL);
INSERT INTO "elements" VALUES(793,'WmfPlaceableFileHeader','Placeable metafile',19,36,NULL);
INSERT INTO "elements" VALUES(794,'EmfPlusRecordType','Graphic commands',19,37,NULL);
INSERT INTO "elements" VALUES(795,'WrapMode','Texture or gradient is tiled',19,80,NULL);
INSERT INTO "elements" VALUES(796,'*DockPanelSuite','Dock panel suite',2,113,NULL);
INSERT INTO "elements" VALUES(797,'DockContainer','Dock container',2,114,NULL);
INSERT INTO "elements" VALUES(798,'DockPanel','Dock panel',1,49,NULL);
INSERT INTO "elements" VALUES(799,'ChildDockContent','Dock content container',2,115,NULL);
INSERT INTO "elements" VALUES(800,'DockState','Dock state',2,116,NULL);
INSERT INTO "elements" VALUES(801,'DockContent','Dock content enumerations',1,50,NULL);
INSERT INTO "elements" VALUES(802,'*Tools','Common tools',23,30,NULL);
INSERT INTO "elements" VALUES(803,'SoundPlayer','Playback .wav file',23,31,NULL);
INSERT INTO "elements" VALUES(804,'NumericToString','Numeric to string',5,21,NULL);
INSERT INTO "elements" VALUES(805,'StringToNumeric','String to numeric',5,22,NULL);
INSERT INTO "elements" VALUES(806,'CRCTool','Calculate CRC',22,3,NULL);
INSERT INTO "elements" VALUES(807,'ControlInherit','Base class for controls',25,1,NULL);
INSERT INTO "elements" VALUES(808,'Object','Base class of all classes',25,2,NULL);
INSERT INTO "elements" VALUES(809,'MarshalByRefObject','Access to objects',25,3,NULL);
INSERT INTO "elements" VALUES(810,'MarshalByValueComponent','Implements IComponent',25,4,NULL);
INSERT INTO "elements" VALUES(811,'Component','IComponent interface',25,5,NULL);
INSERT INTO "elements" VALUES(812,'*UserClass','User derived class',21,30,NULL);
INSERT INTO "elements" VALUES(813,'ClassContainer','Container of the derived class',21,31,NULL);
INSERT INTO "elements" VALUES(814,'UserConstructor','Constructor of the user class',21,32,NULL);
INSERT INTO "elements" VALUES(815,'UserMethod','Method of the user class',21,33,NULL);
INSERT INTO "elements" VALUES(816,'DoUserMethod','Invokes the method outside a class',21,34,NULL);
INSERT INTO "elements" VALUES(817,'UserField','Field of the user class',21,35,NULL);
INSERT INTO "elements" VALUES(818,'UserFieldRW','Access field outside a class',21,36,NULL);
INSERT INTO "elements" VALUES(819,'UserProperty','Property of the user class',21,37,NULL);
INSERT INTO "elements" VALUES(820,'UserPropertyRW','Access property outside a class',21,38,NULL);
INSERT INTO "elements" VALUES(821,'Lock','Implements a critical section',8,11,NULL);
INSERT INTO "elements" VALUES(822,'UserConst','Constant of the user class',21,39,NULL);
INSERT INTO "elements" VALUES(823,'UserConstR','Access to constant',21,40,NULL);
INSERT INTO "elements" VALUES(824,'UserDestructor','Destructor of the user class',21,41,NULL);
INSERT INTO "elements" VALUES(825,'UserIndexer','Declares the indexer of the user class',21,42,NULL);
INSERT INTO "elements" VALUES(826,'UserIndexerRW','Makes the access indexer',21,43,NULL);
INSERT INTO "elements" VALUES(827,'UserEvent','Declares the user event',21,44,NULL);
INSERT INTO "elements" VALUES(828,'*Fonts','Fonts',19,62,NULL);
INSERT INTO "elements" VALUES(829,'FontFamily','Group of the fonts',19,63,NULL);
INSERT INTO "elements" VALUES(831,'GenericFontFamilies','Generic FontFamily object',19,69,NULL);
INSERT INTO "elements" VALUES(832,'StringFormatFlags','Layout information for strings',19,68,NULL);
INSERT INTO "elements" VALUES(833,'FillMode','Fill mode',19,81,NULL);
INSERT INTO "elements" VALUES(834,'GraphicsPath','Series of connected curves',19,52,NULL);
INSERT INTO "elements" VALUES(835,'Region','Graphics shape',19,61,NULL);
INSERT INTO "elements" VALUES(836,'MatrixOrder','Order for transform operations',19,79,NULL);
INSERT INTO "elements" VALUES(837,'CopyPixelOperation','Copy pixel operation',19,82,NULL);
INSERT INTO "elements" VALUES(838,'CharacterRange','Range of character',19,85,NULL);
INSERT INTO "elements" VALUES(839,'PsBatch','Batch automation routine',18,21,NULL);
INSERT INTO "elements" VALUES(840,'PsBatchOptions','Options a Batch comman',18,32,NULL);
INSERT INTO "elements" VALUES(841,'PsBatchDestinationType','Destination for the processed files',18,59,NULL);
INSERT INTO "elements" VALUES(842,'*Ps enumerations','Ps enumerations',18,50,NULL);
INSERT INTO "elements" VALUES(843,'PsFileNamingType','Naming options for the batch',18,51,NULL);
INSERT INTO "elements" VALUES(844,'PsFileNaming','Array of the file naming options',18,35,NULL);
INSERT INTO "elements" VALUES(845,'PsChangeMode','Color mode to use',18,52,NULL);
INSERT INTO "elements" VALUES(846,'*Ps change document','Ps change document',18,17,NULL);
INSERT INTO "elements" VALUES(847,'PsDocChangeMode','Changes color mode',18,22,NULL);
INSERT INTO "elements" VALUES(848,'PsDocResizeImage','Changes image size',18,25,NULL);
INSERT INTO "elements" VALUES(849,'PsResampleMethod','Method image interpolation',18,53,NULL);
INSERT INTO "elements" VALUES(850,'PsDocResizeCanvas','Changes the canvas',18,28,NULL);
INSERT INTO "elements" VALUES(851,'PsAnchorPosition','Anchor point',18,54,NULL);
INSERT INTO "elements" VALUES(852,'PsDocRotateCanvas','Rotates the canvas',18,29,NULL);
INSERT INTO "elements" VALUES(853,'PsDocFlipCanvas','Flips the canvas',18,27,NULL);
INSERT INTO "elements" VALUES(854,'PsDirection','Flip direction',18,55,NULL);
INSERT INTO "elements" VALUES(855,'PsDocCrop','Crops the document',18,26,NULL);
INSERT INTO "elements" VALUES(856,'PsPreferences','Application preferences',18,13,NULL);
INSERT INTO "elements" VALUES(857,'PsRulerUnits','Ruler unit',18,56,NULL);
INSERT INTO "elements" VALUES(858,'PsTypeUnits','Characters unit',18,57,NULL);
INSERT INTO "elements" VALUES(859,'PsColorPicker','Color picker to use',18,58,NULL);
INSERT INTO "elements" VALUES(860,'ItemsArray','Array of the items',12,14,NULL);
INSERT INTO "elements" VALUES(861,'PsPDFSaveOptions','PDF save options',18,46,NULL);
INSERT INTO "elements" VALUES(862,'IdPDFExportPreset','Export settings',18,71,NULL);
INSERT INTO "elements" VALUES(863,'IdPDFExportPresets','Export settings collection',18,72,NULL);
INSERT INTO "elements" VALUES(864,'PsDocSelection','Selected area',18,30,NULL);
INSERT INTO "elements" VALUES(865,'GlobalHook','Mouse and keyboard activities',14,6,NULL);
INSERT INTO "elements" VALUES(866,'ChildStatusStrip','StatusStrip container',2,49,NULL);
INSERT INTO "elements" VALUES(867,'ToolStripStatusLabel','Label on StatusStrip',2,50,NULL);
INSERT INTO "elements" VALUES(868,'ToolStripProgressBar','Progress bar on StatusStrip',2,51,NULL);
INSERT INTO "elements" VALUES(869,'ToolStripSplitButton','Drop-down button on StatusStrip',2,52,NULL);
INSERT INTO "elements" VALUES(870,'ToolStripDropDownButton','Drop-down button on StatusStrip',2,53,NULL);
INSERT INTO "elements" VALUES(871,'ToolStripDropDown','Drop-down menu',2,104,NULL);
INSERT INTO "elements" VALUES(872,'GtkLabel','Widget that displays text',26,1,NULL);
INSERT INTO "elements" VALUES(873,'GtkFixedContainer','Container with fixed coordinates',26,2,NULL);
INSERT INTO "elements" VALUES(874,'GtkMessageDialog','Convenient message window',26,3,NULL);
INSERT INTO "elements" VALUES(875,'GtkButton','Widget with clicked event',26,4,NULL);
INSERT INTO "elements" VALUES(876,'GtkTextView','Widget that displays a TextBuffer',26,5,NULL);
INSERT INTO "elements" VALUES(877,'Settings','Application settings',4,18,NULL);
INSERT INTO "elements" VALUES(878,'ProtectString','Encrypts/decrypts string',22,4,NULL);
INSERT INTO "elements" VALUES(879,'*Input Simulators','Input Simulators',14,70,NULL);
INSERT INTO "elements" VALUES(880,'MouseEvent','Mouse event simulator',14,71,NULL);
INSERT INTO "elements" VALUES(881,'KeyEvent','Key event simulator',14,72,NULL);
INSERT INTO "elements" VALUES(882,'VirtualKeyCode','Virtual-key codes',14,73,NULL);
INSERT INTO "elements" VALUES(883,'MultiElement','Container',4,19,NULL);
INSERT INTO "elements" VALUES(884,'EditMulti','MultiElement editor',1,51,NULL);
INSERT INTO "elements" VALUES(885,'ChildStatusBar','StatusBar container',2,54,NULL);
INSERT INTO "elements" VALUES(886,'StatusBarPanel','Panel in a StatusBar',2,57,NULL);
INSERT INTO "elements" VALUES(887,'*GongShell','GongShell',2,29,NULL);
INSERT INTO "elements" VALUES(888,'ShellView','System explorer control',2,30,NULL);
INSERT INTO "elements" VALUES(889,'ShellTreeView','System tree view control',2,31,NULL);
INSERT INTO "elements" VALUES(890,'ShellComboBox','Display Windows Shell namespace',2,32,NULL);
INSERT INTO "elements" VALUES(891,'ShellToolBar','Filename toolbar',2,33,NULL);
INSERT INTO "elements" VALUES(892,'ShellNameComboBox','Filename combo box',2,34,NULL);
INSERT INTO "elements" VALUES(893,'ShellFilterComboBox','File-filter combo box',2,35,NULL);
INSERT INTO "elements" VALUES(894,'ShellPlacesToolBar','Toolbar common places',2,36,NULL);
INSERT INTO "elements" VALUES(895,'ShellViewStyle','Shell view style',2,37,NULL);
INSERT INTO "elements" VALUES(896,'ShellShowHidden','Shell show hidden enumerations',2,38,NULL);
INSERT INTO "elements" VALUES(897,'*TableLayout','TableLayout',2,78,NULL);
INSERT INTO "elements" VALUES(898,'ChildTableLayout','Table layout container',2,79,NULL);
INSERT INTO "elements" VALUES(899,'TableLayoutColumns','Table layout columns',2,80,NULL);
INSERT INTO "elements" VALUES(900,'TableLayoutRows','Table layout rows',2,81,NULL);
INSERT INTO "elements" VALUES(901,'TableLayoutCell','Table layout cell',2,82,NULL);
INSERT INTO "elements" VALUES(902,'SDK','HiAsm SDK',27,1,NULL);
INSERT INTO "elements" VALUES(903,'SDKBuilder','SDK builder',27,4,NULL);
INSERT INTO "elements" VALUES(904,'SDKDraw','Draw project',27,5,NULL);
INSERT INTO "elements" VALUES(905,'*Camera','Camera',23,40,NULL);
INSERT INTO "elements" VALUES(906,'EmguCapture','Capture camera',23,41,NULL);
INSERT INTO "elements" VALUES(907,'EmguVideoWriter','Images to video',23,42,NULL);
INSERT INTO "elements" VALUES(908,'EmguImageBox','Image box',23,43,NULL);
INSERT INTO "elements" VALUES(909,'EmguImageDetector','Detect object in the image',23,44,NULL);
INSERT INTO "elements" VALUES(910,'EmguCameraHost','Camera Host',23,45,NULL);
INSERT INTO "elements" VALUES(911,'EmguCameraClient','Camera Client',23,46,NULL);
INSERT INTO "elements" VALUES(912,'SDKEvents','SDK events handler',27,6,NULL);
INSERT INTO "elements" VALUES(913,'SDKView','SDK editor',27,8,NULL);
INSERT INTO "elements" VALUES(914,'SDKToolbox','Toolbox for SDK',27,9,NULL);
INSERT INTO "elements" VALUES(915,'ChildToolStripPanel','Collections of controls',2,58,NULL);
INSERT INTO "elements" VALUES(916,'SDKCallbackType','SDK events',27,7,NULL);
INSERT INTO "elements" VALUES(917,'PropertyGrid','Properties of the element',2,27,NULL);
INSERT INTO "elements" VALUES(918,'SDKLog','SDK log',27,2,NULL);
INSERT INTO "elements" VALUES(919,'SDKCommands','SDK commands',27,10,NULL);
INSERT INTO "elements" VALUES(920,'SDKProjects','SDK projects',27,3,NULL);
INSERT INTO "elements" VALUES(921,'PropertyValueChangedEventArgs','Event of a PropertyGrid',2,61,NULL);
INSERT INTO "elements" VALUES(922,'GridItem','Row in a PropertyGrid',13,14,NULL);
INSERT INTO "elements" VALUES(923,'SDKProperties','Properties window',27,11,NULL);
INSERT INTO "elements" VALUES(924,'SDKShare','SDK Share interface',27,12,NULL);
INSERT INTO "elements" VALUES(925,'WindowGeometry','Window geometry',2,77,NULL);
INSERT INTO "elements" VALUES(926,'Targa','Represents the Targa format of the image.',19,22,NULL);
INSERT INTO "elements" VALUES(927,'ChromiumWebBrowser','Chrome WebBrowser',2,28,NULL);
INSERT INTO "elements" VALUES(928,'SvgDocument','SVG document',19,21,NULL);
INSERT INTO "elements" VALUES(929,'EncodingDetect','Recognize encoding',10,59,NULL);
INSERT INTO "elements" VALUES(930,'hcButton','Button',28,1,NULL);
INSERT INTO "elements" VALUES(931,'hcVisualText','Visual text',28,2,NULL);
INSERT INTO "elements" VALUES(932,'hcListBox','ListBox',28,3,NULL);
INSERT INTO "elements" VALUES(933,'*Core_Tools','Tools',28,4,NULL);
INSERT INTO "elements" VALUES(934,'hcHub','Flow hub',28,5,NULL);
INSERT INTO "elements" VALUES(935,'hcDoData','Data to flow',28,6,NULL);
INSERT INTO "elements" VALUES(936,'hcIf_else','Logic hub',28,7,NULL);
INSERT INTO "elements" VALUES(937,'hcTimer','Timer',28,8,NULL);
INSERT INTO "elements" VALUES(938,'hcMath','Math operations',28,9,NULL);
INSERT INTO "elements" VALUES(939,'hcFor','Loop count',28,10,NULL);
INSERT INTO "elements" VALUES(940,'hcRandom','Random generator',28,11,NULL);
INSERT INTO "elements" VALUES(941,'hcMessage','Message window',28,12,NULL);
INSERT INTO "elements" VALUES(942,'hcBeep','Beeper',28,13,NULL);
INSERT INTO "elements" VALUES(943,'hcStrCat','String concatination',28,14,NULL);
INSERT INTO "elements" VALUES(944,'*Core_Environment','Environment',28,15,NULL);
INSERT INTO "elements" VALUES(945,'hcTrace','Trace message',28,16,NULL);
INSERT INTO "elements" VALUES(946,'hcCommander','Call command',28,17,NULL);
INSERT INTO "elements" VALUES(947,'hcCommanHandler','Commnad handler',28,18,NULL);
INSERT INTO "elements" VALUES(948,'hcSDKEvents','SDK events',28,19,NULL);
INSERT INTO "elements" VALUES(949,'hcKeyHandler','Keyboard handler',28,20,NULL);
INSERT INTO "elements" VALUES(950,'hcMouseHandler','Mouse handler',28,21,NULL);
INSERT INTO "elements" VALUES(951,'*Core_Elements','Elements',28,22,NULL);
INSERT INTO "elements" VALUES(952,'hcAddElement','Adds element',28,23,NULL);
INSERT INTO "elements" VALUES(953,'hcMoveElement','Moves element',28,24,NULL);
INSERT INTO "elements" VALUES(954,'hcConnectElement','Connect elements',28,25,NULL);
INSERT INTO "elements" VALUES(955,'ColorPicker','Color select control',2,20,NULL);
INSERT INTO "elements" VALUES(956,'PolymorphMulti','Polymorphic container',4,20,NULL);
CREATE TABLE files_link(file_id int, el_id int);
COMMIT;
